/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_SecurityDemo_R_H__
#define __Elastos_DevSamples_SecurityDemo_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace SecurityDemo {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class drawable {
        public: static const int colorleaf = 0x7f020000;
        public: static const int cupple = 0x7f020001;
        public: static const int earth = 0x7f020002;
        public: static const int icon = 0x7f020003;
        public: static const int leaf = 0x7f020004;
    };
    public: class id {
        public: static const int Button1 = 0x7f050000;
        public: static const int Button2 = 0x7f050001;
        public: static const int Button3 = 0x7f050002;
        public: static const int Button4 = 0x7f050003;
        public: static const int Button5 = 0x7f050004;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};

#endif // __Elastos_DevSamples_SecurityDemo_R_H__
