/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_PackageInstaller_R_H__
#define __Elastos_Droid_PackageInstaller_R_H__
#include <elatypes.h>
namespace Elastos {
namespace Droid {
namespace PackageInstaller {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class color {
        public: static const int shadow = 0x7f040000;
        public: static const int transparent = 0x7f040001;
    };
    public: class drawable {
        public: static const int ic_fail = 0x7f020000;
        public: static const int ic_result_status = 0x7f020001;
        public: static const int ic_success = 0x7f020002;
    };
    public: class id {
        public: static const int activity_text = 0x7f070017;
        public: static const int app_icon = 0x7f070001;
        public: static const int app_name = 0x7f070002;
        public: static const int app_snippet = 0x7f070000;
        public: static const int buttons_panel = 0x7f07000f;
        public: static const int cancel_button = 0x7f07000b;
        public: static const int center_explanation = 0x7f070013;
        public: static const int center_text = 0x7f070012;
        public: static const int device_manager_button = 0x7f07001d;
        public: static const int devicelist = 0x7f070016;
        public: static const int divider = 0x7f070006;
        public: static const int done_button = 0x7f070010;
        public: static const int filler = 0x7f070007;
        public: static const int install_confirm_panel = 0x7f07000e;
        public: static const int install_confirm_question = 0x7f070005;
        public: static const int launch_button = 0x7f070011;
        public: static const int leftSpacer = 0x7f07000a;
        public: static const int ok_button = 0x7f07000c;
        public: static const int ok_panel = 0x7f07001a;
        public: static const int pager = 0x7f070009;
        public: static const int privacylist = 0x7f070015;
        public: static const int progress_bar = 0x7f070004;
        public: static const int rightSpacer = 0x7f07000d;
        public: static const int scrollview = 0x7f070014;
        public: static const int tabscontainer = 0x7f070008;
        public: static const int top_divider = 0x7f070003;
        public: static const int uninstall_activity_snippet = 0x7f070018;
        public: static const int uninstall_confirm = 0x7f070019;
        public: static const int uninstall_holder = 0x7f07001b;
        public: static const int uninstalling_scrollview = 0x7f07001c;
    };
    public: class layout {
        public: static const int app_details = 0x7f030000;
        public: static const int install_confirm = 0x7f030001;
        public: static const int install_start = 0x7f030002;
        public: static const int label = 0x7f030003;
        public: static const int op_progress = 0x7f030004;
        public: static const int permissions_list = 0x7f030005;
        public: static const int uninstall_confirm = 0x7f030006;
        public: static const int uninstall_progress = 0x7f030007;
    };
    public: class string {
        public: static const int Parse_error_dlg_text = 0x7f050038;
        /**  Dialog attributes to indicate parse errors 
         */
        public: static const int Parse_error_dlg_title = 0x7f050037;
        /**  Tab label for all permissions of an app being installed [CHAR LIMIT=20] 
         */
        public: static const int allPerms = 0x7f05003a;
        /**  Message of dialog asking user if they would allow an application to be an install source. 
         */
        public: static const int allow_source_dlg_text = 0x7f05001e;
        /**  Title of dialog asking user if they would allow an application to be an install source. 
         */
        public: static const int allow_source_dlg_title = 0x7f05001d;
        public: static const int app_name = 0x7f050000;
        public: static const int app_not_found_dlg_text = 0x7f050027;
        public: static const int app_not_found_dlg_title = 0x7f050026;
        public: static const int cancel = 0x7f050005;
        /**  Tab label for permissions related to device behavior [CHAR LIMIT=20] 
         */
        public: static const int devicePerms = 0x7f05003c;
        public: static const int dlg_app_replacement_statement = 0x7f050021;
        public: static const int dlg_app_replacement_title = 0x7f050020;
        /**  strings related to uninstall activity 
         */
        public: static const int dlg_ok = 0x7f050025;
        /**  Dialog attributes when replacing system app 
         */
        public: static const int dlg_sys_app_replacement_statement = 0x7f050022;
        public: static const int done = 0x7f050003;
        public: static const int grant_confirm_question = 0x7f05003e;
        public: static const int install = 0x7f050002;
        /**  Message for installing a new app that requires some permissions [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question = 0x7f050009;
        /**  Message for installing a new app that does not require permissions [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question_no_perms = 0x7f05000a;
        /**  Message for updating an existing app [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question_update = 0x7f05000b;
        /**  Message for updating an existing app, no permissions [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question_update_no_perms = 0x7f05000d;
        /**  Message for updating an existing system app [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question_update_system = 0x7f05000c;
        /**  Message for updating an existing system app, no permissions [CHAR LIMIT=NONE] 
         */
        public: static const int install_confirm_question_update_system_no_perms = 0x7f05000e;
        public: static const int install_done = 0x7f050008;
        public: static const int install_failed = 0x7f05000f;
        /**  Reason displayed when installation fails because the package specifies it is compatible
        only with a CPU that the current phone doesn't have. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_cpu_abi_incompatible = 0x7f050013;
        /**  Reason displayed when installation fails because the package was deleted during the
        installation process. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_file_not_found = 0x7f050014;
        /**  Reason displayed when installation fails because the package an existing package is
        installed with a conflicting package author signature [CHAR LIMIT=100] 
         */
        public: static const int install_failed_inconsistent_certificates = 0x7f050011;
        /**  Reason displayed when installation fails because the installation package itself is invalid
        in some way (e.g., corrupt) [CHAR LIMIT=100] 
         */
        public: static const int install_failed_invalid_apk = 0x7f050010;
        /**  Message presented when an application could not be installed on the phone for some reason. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_msg = 0x7f050017;
        /**  Reason displayed when installation fails because the package specifies a minimum compatible
        OS version that is newer than our current OS version. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_older_sdk = 0x7f050012;
        /**  Reason displayed when installation fails because the package could not be verified
        because the package verifier rejected it. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_verify_failed = 0x7f050015;
        /**  Reason displayed when installation fails because the package could not be verified
        before the internal system timer expired. [CHAR LIMIT=100] 
         */
        public: static const int install_failed_verify_timeout = 0x7f050016;
        public: static const int installing = 0x7f050007;
        public: static const int launch = 0x7f050018;
        public: static const int manage_applications = 0x7f05001f;
        /**  String on a button that leads to the "device administrator" configuration setting where a
        user will be able to disable the device administrator in order to uninstall
        it. [CHAR LIMIT=50] 
         */
        public: static const int manage_device_administrators = 0x7f050035;
        /**  Tab label for new permissions being added to an existing app [CHAR LIMIT=20] 
         */
        public: static const int newPerms = 0x7f050039;
        public: static const int next = 0x7f050001;
        /**  Body text for new tab when there are no new permissions [CHAR LIMIT=NONE] 
         */
        public: static const int no_new_perms = 0x7f05003d;
        public: static const int ok = 0x7f05001b;
        public: static const int out_of_space_dlg_text = 0x7f050024;
        public: static const int out_of_space_dlg_title = 0x7f050023;
        /**  Tab label for permissions related to user privacy [CHAR LIMIT=20] 
         */
        public: static const int privacyPerms = 0x7f05003b;
        /**  TODO REMOVE LATER 
         */
        public: static const int security_settings_desc = 0x7f050004;
        public: static const int settings = 0x7f05001c;
        public: static const int uninstall_activity_text = 0x7f05002a;
        public: static const int uninstall_application_text = 0x7f05002b;
        public: static const int uninstall_application_text_all_users = 0x7f05002c;
        /**  syntax error in translation for uninstall_application_text_all_users (5574704453233525222) org.xmlpull.v1.XmlPullParserException: expected: /string read: b (position:END_TAG </b>@1:122 in     <string name="uninstall_application_text_all_users" msgid="5574704453233525222">"გსურთ ამ აპის დეინსტალაცია ყველა"</b>" მომხმარებილის "<b>"-თვის? აპლიკაცია და მისი მონაცემენბი წაიშლება ყველა"</b>" მომხმარებლის "<b>"-თვის მოწყობილობაზე."</string>
)  
         */
        public: static const int uninstall_application_text_user = 0x7f05002d;
        public: static const int uninstall_application_title = 0x7f050028;
        /**  String presented to the user when uninstalling a package failed because a device owner
         has marked the the target package as not able to be uninstalled [CHAR LIMIT=80] 
         */
        public: static const int uninstall_blocked_device_owner = 0x7f050034;
        /**  String presented to the user when uninstalling a package failed because a profile owner
         has marked the the target package as not able to be uninstalled [CHAR LIMIT=80] 
         */
        public: static const int uninstall_blocked_profile_owner = 0x7f050033;
        public: static const int uninstall_done = 0x7f050030;
        public: static const int uninstall_failed = 0x7f050031;
        /**  String presented to the user when uninstalling a package failed because the target package
        is a current device administrator [CHAR LIMIT=80] 
         */
        public: static const int uninstall_failed_device_policy_manager = 0x7f050032;
        public: static const int uninstall_failed_msg = 0x7f050036;
        public: static const int uninstall_update_text = 0x7f05002e;
        public: static const int uninstall_update_title = 0x7f050029;
        public: static const int uninstalling = 0x7f05002f;
        public: static const int unknown = 0x7f050006;
        /**  Message presented in a dialog box when a package is requested to be installed, but the "Allow unknown applications" checkbox is not enabled. [CHAR LIMIT=100] 
         */
        public: static const int unknown_apps_dlg_text = 0x7f05001a;
        public: static const int unknown_apps_dlg_title = 0x7f050019;
    };
    public: class style {
        public: static const int Theme_AlertDialogActivity = 0x7f060002;
        public: static const int Theme_DialogWhenLarge = 0x7f060001;
        public: static const int padded = 0x7f060000;
    };
};
};
};
};

#endif // __Elastos_Droid_PackageInstaller_R_H__
