/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_PropertyDemo_R_H__
#define __Elastos_Droid_DevSamples_PropertyDemo_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace PropertyDemo {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int bt_getBoolean = 0x7f050007;
        public: static const int bt_getByte = 0x7f050001;
        public: static const int bt_getChar16 = 0x7f050005;
        public: static const int bt_getChar8 = 0x7f050003;
        public: static const int bt_getDouble = 0x7f050011;
        public: static const int bt_getFloat = 0x7f05000f;
        public: static const int bt_getInt16 = 0x7f050009;
        public: static const int bt_getInt32 = 0x7f05000b;
        public: static const int bt_getInt64 = 0x7f05000d;
        public: static const int bt_getInterface = 0x7f050015;
        public: static const int bt_getString = 0x7f050013;
        public: static const int bt_setBoolean = 0x7f050008;
        public: static const int bt_setByte = 0x7f050002;
        public: static const int bt_setChar16 = 0x7f050006;
        public: static const int bt_setChar8 = 0x7f050004;
        public: static const int bt_setDouble = 0x7f050012;
        public: static const int bt_setFloat = 0x7f050010;
        public: static const int bt_setInt16 = 0x7f05000a;
        public: static const int bt_setInt32 = 0x7f05000c;
        public: static const int bt_setInt64 = 0x7f05000e;
        public: static const int bt_setInterface = 0x7f050016;
        public: static const int bt_setString = 0x7f050014;
        public: static const int tx_result = 0x7f050000;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_PropertyDemo_R_H__
