/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_VideoPlayerDemo_R_H__
#define __Elastos_Droid_DevSamples_VideoPlayerDemo_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace VideoPlayerDemo {
class R {
    public: class about {
        public: static const int imgview_back = 0x7f080001;
        public: static const int iv_logo = 0x7f080003;
        public: static const int layout_bottom = 0x7f080002;
        public: static const int layout_title = 0x7f080000;
        public: static const int layout_version = 0x7f080005;
        public: static const int tv_app_name = 0x7f080004;
        public: static const int tv_app_version = 0x7f080006;
    };
    public: class attr {
    };
    public: class color {
        public: static const int black = 0x7f040003;
        public: static const int main_title_bgcolor = 0x7f040001;
        public: static const int title_bar_background = 0x7f040000;
        public: static const int white = 0x7f040002;
    };
    public: class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public: static const int activity_horizontal_margin = 0x7f050000;
        public: static const int activity_vertical_margin = 0x7f050001;
        public: static const int albumart_height = 0x7f050013;
        public: static const int albumart_width = 0x7f050012;
        /**  About MusicPlayer 
         */
        public: static const int arrow_width = 0x7f05000b;
        public: static const int big_logo_height = 0x7f05000e;
        public: static const int big_logo_margin_top = 0x7f05000c;
        public: static const int big_logo_width = 0x7f05000d;
        public: static const int foot_height = 0x7f050008;
        public: static const int logo_height = 0x7f050004;
        public: static const int logo_width = 0x7f050003;
        /**  Play Activity 
         */
        public: static const int play_foot_height = 0x7f05000f;
        public: static const int play_mode_view_width = 0x7f050007;
        public: static const int play_volume_bar_width = 0x7f050010;
        public: static const int search_edittext_width = 0x7f050005;
        public: static const int tab_btn_textsize = 0x7f050009;
        public: static const int tab_btn_textsize_focus = 0x7f05000a;
        public: static const int tab_width = 0x7f050006;
        /**  MainActivity 
         */
        public: static const int title_bar_height = 0x7f050002;
        public: static const int title_icon_margin_left = 0x7f050011;
    };
    public: class drawable {
        public: static const int bg_border_hi = 0x7f020000;
        public: static const int bg_border_hi_down = 0x7f020001;
        public: static const int bg_border_lo = 0x7f020002;
        public: static const int bg_border_lo_down = 0x7f020003;
        public: static const int btn_add_new_playlist = 0x7f020004;
        public: static const int btn_edit = 0x7f020005;
        public: static const int btn_search = 0x7f020006;
        public: static const int btn_search_hightlight = 0x7f020007;
        public: static const int icon = 0x7f020008;
        public: static const int main_about_btn_style = 0x7f020009;
        public: static const int main_bottom_bg = 0x7f02000a;
        public: static const int main_bottom_btn_pause = 0x7f02000b;
        public: static const int main_bottom_btn_play = 0x7f02000c;
        public: static const int main_btn_bg_selector = 0x7f02000d;
        public: static const int main_btn_edit_selector = 0x7f02000e;
        public: static const int main_tab_right_btn_style = 0x7f02000f;
        public: static const int menu_delete = 0x7f020010;
        public: static const int menu_detail = 0x7f020011;
        public: static const int menu_share = 0x7f020012;
        public: static const int music_logo = 0x7f020013;
        public: static const int music_seekbar_background = 0x7f020014;
        public: static const int music_seekbar_progress = 0x7f020015;
        public: static const int music_seekbar_style = 0x7f020016;
        public: static const int music_seekbar_thumb = 0x7f020017;
        public: static const int music_unknown = 0x7f020018;
        public: static const int pause_btn = 0x7f020019;
        public: static const int pause_btn_down = 0x7f02001a;
        public: static const int pause_btn_selector = 0x7f02001b;
        public: static const int play_all_loop = 0x7f02001c;
        public: static const int play_background = 0x7f02001d;
        public: static const int play_btn = 0x7f02001e;
        public: static const int play_btn_down = 0x7f02001f;
        public: static const int play_btn_front_selector = 0x7f020020;
        public: static const int play_btn_more = 0x7f020021;
        public: static const int play_btn_next_selector = 0x7f020022;
        public: static const int play_btn_selector = 0x7f020023;
        public: static const int play_buttons_right_selector = 0x7f020024;
        public: static const int play_front = 0x7f020025;
        public: static const int play_front_down = 0x7f020026;
        public: static const int play_mode_all_loop_selector = 0x7f020027;
        public: static const int play_mode_order_selector = 0x7f020028;
        public: static const int play_mode_random_selector = 0x7f020029;
        public: static const int play_mode_single_loop_selector = 0x7f02002a;
        public: static const int play_more_mode_down = 0x7f02002b;
        public: static const int play_more_selector = 0x7f02002c;
        public: static const int play_next = 0x7f02002d;
        public: static const int play_next_down = 0x7f02002e;
        public: static const int play_order = 0x7f02002f;
        public: static const int play_random = 0x7f020030;
        public: static const int play_right_play_list_background = 0x7f020031;
        public: static const int play_right_volume_background = 0x7f020032;
        public: static const int play_single_loop = 0x7f020033;
        public: static const int play_switch_btn_selector = 0x7f020034;
        public: static const int play_switch_current = 0x7f020035;
        public: static const int play_switch_next = 0x7f020036;
        public: static const int search_btn_selector = 0x7f020037;
        public: static const int tab_btn_focus = 0x7f020038;
        public: static const int tab_btn_selector = 0x7f020039;
        public: static const int title_arrow_back = 0x7f02003a;
    };
    public: class edit {
        public: static const int image_view = 0x7f090001;
        public: static const int layout_title = 0x7f090000;
        public: static const int tv_label = 0x7f090002;
    };
    public: class file_opt {
        public: static const int btn_all_pick = 0x7f0e0000;
        public: static const int btn_delete = 0x7f0e0002;
        public: static const int btn_folder = 0x7f0e0003;
        public: static const int btn_share = 0x7f0e0001;
    };
    public: class id {
        public: static const int videoView1 = 0x7f0d0000;
    };
    public: class item {
        public: static const int main_btn_more = 0x7f100004;
        public: static const int main_imgview_left = 0x7f100000;
        public: static const int main_tv_byte = 0x7f100003;
        public: static const int main_tv_singer = 0x7f100002;
        public: static const int main_tv_song = 0x7f100001;
        public: static const int main_tv_time = 0x7f100005;
    };
    public: class label {
        public: static const int tv_key = 0x7f0f0000;
        public: static const int tv_split = 0x7f0f0001;
        public: static const int tv_value = 0x7f0f0002;
    };
    public: class layout {
        public: static const int activity_about = 0x7f030000;
        public: static const int activity_edit = 0x7f030001;
        public: static const int activity_main = 0x7f030002;
        public: static const int activity_play = 0x7f030003;
        public: static const int activity_search = 0x7f030004;
        public: static const int main = 0x7f030005;
        public: static const int view_file_opeartion = 0x7f030006;
        public: static const int view_label = 0x7f030007;
        public: static const int view_main_item = 0x7f030008;
        public: static const int view_textview = 0x7f030009;
    };
    public: class main {
        public: static const int content_listview = 0x7f0a0004;
        public: static const int foot_btn_pause = 0x7f0a000a;
        public: static const int foot_btn_play = 0x7f0a0009;
        public: static const int foot_imgview_album_art = 0x7f0a0006;
        public: static const int foot_layout = 0x7f0a0005;
        public: static const int foot_tv_singer = 0x7f0a0008;
        public: static const int foot_tv_song = 0x7f0a0007;
        public: static const int list_layout = 0x7f0a0002;
        public: static const int seekbar_music = 0x7f0a0003;
        public: static const int title_layout = 0x7f0a0000;
        public: static const int title_tv_label = 0x7f0a0001;
    };
    public: class play {
        public: static const int btn_mode_all_loop = 0x7f0b001f;
        public: static const int btn_mode_order = 0x7f0b0022;
        public: static const int btn_mode_random = 0x7f0b0021;
        public: static const int btn_mode_single_loop = 0x7f0b0020;
        public: static const int btn_more = 0x7f0b0024;
        public: static const int btn_next = 0x7f0b0023;
        public: static const int btn_pause = 0x7f0b001c;
        public: static const int btn_play = 0x7f0b001d;
        public: static const int btn_previous = 0x7f0b001e;
        public: static const int btn_switch_left = 0x7f0b000c;
        public: static const int btn_switch_right = 0x7f0b000d;
        public: static const int imgview_right_delete = 0x7f0b0006;
        public: static const int imgview_right_detail = 0x7f0b0002;
        public: static const int imgview_right_share = 0x7f0b0004;
        public: static const int imgview_title_back = 0x7f0b0009;
        public: static const int iv_album_art = 0x7f0b0011;
        public: static const int layout_foot = 0x7f0b000f;
        public: static const int layout_play = 0x7f0b001b;
        public: static const int layout_playlist = 0x7f0b0025;
        public: static const int layout_right_delete = 0x7f0b0005;
        public: static const int layout_right_detail = 0x7f0b0001;
        public: static const int layout_right_share = 0x7f0b0003;
        public: static const int layout_song = 0x7f0b000e;
        public: static const int layout_song_info = 0x7f0b0010;
        public: static const int layout_song_words = 0x7f0b0014;
        public: static const int layout_song_words_content = 0x7f0b0017;
        public: static const int layout_title = 0x7f0b0008;
        public: static const int layout_volume_bar = 0x7f0b0000;
        public: static const int listview_playlist = 0x7f0b0026;
        public: static const int radio_group = 0x7f0b000b;
        public: static const int seekbar_music = 0x7f0b001a;
        public: static const int seekbar_volume = 0x7f0b0007;
        public: static const int tv_album_and_name = 0x7f0b0012;
        public: static const int tv_current_time = 0x7f0b0018;
        public: static const int tv_singer = 0x7f0b0013;
        public: static const int tv_song_name = 0x7f0b0015;
        public: static const int tv_song_words = 0x7f0b0016;
        public: static const int tv_title_song = 0x7f0b000a;
        public: static const int tv_total_time = 0x7f0b0019;
    };
    public: class search {
        public: static const int imgview_title_back = 0x7f0c0001;
        public: static const int title_btn_edit = 0x7f0c0002;
        public: static const int title_btn_search = 0x7f0c0003;
        public: static const int title_layout = 0x7f0c0000;
    };
    public: class string {
        public: static const int about = 0x7f060003;
        public: static const int add_new_playlist = 0x7f060012;
        public: static const int album = 0x7f06000f;
        public: static const int all_pick = 0x7f060013;
        public: static const int app_name = 0x7f060000;
        public: static const int colon = 0x7f06001c;
        public: static const int delete_ = 0x7f060015;
        public: static const int detail = 0x7f060017;
        public: static const int detail_info = 0x7f060016;
        public: static const int developer = 0x7f06001b;
        public: static const int edit = 0x7f060011;
        public: static const int elastos_os = 0x7f06001d;
        public: static const int local_all_music = 0x7f060004;
        public: static const int look_detail = 0x7f060018;
        public: static const int loop_play = 0x7f06000b;
        public: static const int more = 0x7f060002;
        public: static const int order_play = 0x7f06000e;
        public: static const int play = 0x7f060007;
        public: static const int play_list = 0x7f060010;
        public: static const int random_play = 0x7f06000d;
        public: static const int root = 0x7f060006;
        public: static const int search = 0x7f060005;
        public: static const int share = 0x7f060014;
        public: static const int singer = 0x7f060009;
        public: static const int single_loop = 0x7f06000c;
        public: static const int song = 0x7f060008;
        public: static const int song_name = 0x7f060001;
        public: static const int song_words = 0x7f060019;
        public: static const int unknown_singer = 0x7f06000a;
        public: static const int version = 0x7f06001a;
    };
    public: class style {
        public: static const int edittext_search = 0x7f070000;
        /**  MainActivity Tab 
         */
        public: static const int main_btn_about = 0x7f070001;
        public: static const int main_btn_search = 0x7f070007;
        public: static const int main_tab_btn_play_mode = 0x7f070003;
        public: static const int main_tab_btn_right = 0x7f070002;
        public: static const int main_tab_mode_btn_style = 0x7f070004;
        public: static const int main_tab_mode_layout_style = 0x7f070005;
        /**  PlayActivity 
         */
        public: static const int play_btn = 0x7f070008;
        public: static const int play_music_seekbar = 0x7f07000a;
        public: static const int play_right_volume = 0x7f07000b;
        public: static const int play_switch_btn_style = 0x7f070009;
        public: static const int tab_btn = 0x7f070006;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_VideoPlayerDemo_R_H__
