//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    VideoCaptureFactory.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_VIDEOCAPTUREFACTORY_CALLBACK_DEC_HH
#define ELASTOS_VIDEOCAPTUREFACTORY_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_VideoCaptureFactory_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Media {

struct ElaVideoCaptureFactoryCallback
{
    Int32 (*elastos_ChromiumCameraInfo_getNumberOfCameras)(IInterface* appContext);
    AutoPtr<IInterface> (*elastos_ChromiumCameraInfo_getAt)(Int32 index);
    Int32 (*elastos_ChromiumCameraInfo_getId)(IInterface* obj);
    String (*elastos_ChromiumCameraInfo_getDeviceName)(IInterface* obj);
    Int32 (*elastos_ChromiumCameraInfo_getOrientation)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_VideoCaptureFactory_createVideoCapture)(IInterface* context, Int32 id, Int64 nativeVideoCaptureDeviceAndroid);
    AutoPtr<ArrayOf<IInterface*> > (*elastos_VideoCaptureFactory_getDeviceSupportedFormats)(Int32 id);
    Int32 (*elastos_VideoCaptureFactory_getCaptureFormatWidth)(IInterface* format);
    Int32 (*elastos_VideoCaptureFactory_getCaptureFormatHeight)(IInterface* format);
    Int32 (*elastos_VideoCaptureFactory_getCaptureFormatFramerate)(IInterface* format);
    Int32 (*elastos_VideoCaptureFactory_getCaptureFormatPixelFormat)(IInterface* format);
};

void* VideoCaptureFactory::ElaVideoCaptureFactoryCallback_Init()
{
    static ElaVideoCaptureFactoryCallback sElaVideoCaptureFactoryCallback;

    sElaVideoCaptureFactoryCallback.elastos_ChromiumCameraInfo_getNumberOfCameras = &VideoCaptureFactory::ChromiumCameraInfo::GetNumberOfCameras;
    sElaVideoCaptureFactoryCallback.elastos_ChromiumCameraInfo_getAt = &VideoCaptureFactory::ChromiumCameraInfo::GetAt;
    sElaVideoCaptureFactoryCallback.elastos_ChromiumCameraInfo_getId = &VideoCaptureFactory::ChromiumCameraInfo::GetId;
    sElaVideoCaptureFactoryCallback.elastos_ChromiumCameraInfo_getDeviceName = &VideoCaptureFactory::ChromiumCameraInfo::GetDeviceName;
    sElaVideoCaptureFactoryCallback.elastos_ChromiumCameraInfo_getOrientation = &VideoCaptureFactory::ChromiumCameraInfo::GetOrientation;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_createVideoCapture = &VideoCaptureFactory::CreateVideoCapture;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_getDeviceSupportedFormats = &VideoCaptureFactory::GetDeviceSupportedFormats;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_getCaptureFormatWidth = &VideoCaptureFactory::GetCaptureFormatWidth;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_getCaptureFormatHeight = &VideoCaptureFactory::GetCaptureFormatHeight;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_getCaptureFormatFramerate = &VideoCaptureFactory::GetCaptureFormatFramerate;
    sElaVideoCaptureFactoryCallback.elastos_VideoCaptureFactory_getCaptureFormatPixelFormat = &VideoCaptureFactory::GetCaptureFormatPixelFormat;

    Elastos_VideoCaptureFactory_InitCallback((Handle32)&sElaVideoCaptureFactoryCallback);
    return &sElaVideoCaptureFactoryCallback;
}

static void* sPElaVideoCaptureFactoryCallback = VideoCaptureFactory::ElaVideoCaptureFactoryCallback_Init();

} // namespace Media
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_VIDEOCAPTUREFACTORY_CALLBACK_DEC_HH
