/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_DialogFragmentDemo_R_H__
#define __Elastos_DevSamples_DialogFragmentDemo_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace DialogFragmentDemo {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
        public: static const int title = 0x7f020001;
    };
    public: class id {
        public: static const int ConfimDialog = 0x7f050005;
        public: static const int DialogInDifferentScreen = 0x7f050008;
        public: static const int EditDialog = 0x7f050006;
        public: static const int LoginDialog = 0x7f050007;
        public: static const int LoginDialogWithoutFragment = 0x7f050009;
        public: static const int id_label_your_name = 0x7f050000;
        public: static const int id_ly = 0x7f05000a;
        public: static const int id_sure_edit_name = 0x7f050002;
        public: static const int id_txt_password = 0x7f050004;
        public: static const int id_txt_username = 0x7f050003;
        public: static const int id_txt_your_name = 0x7f050001;
    };
    public: class layout {
        public: static const int fragment_edit_name = 0x7f030000;
        public: static const int fragment_login_dialog = 0x7f030001;
        public: static const int main = 0x7f030002;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};

#endif // __Elastos_DevSamples_DialogFragmentDemo_R_H__
