/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_BrowserPlugin_R_H__
#define __Elastos_Droid_DevSamples_BrowserPlugin_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace BrowserPlugin {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int sample_browser_plugin = 0x7f020000;
    };
    public: class string {
        public: static const int sample_browser_plugin = 0x7f030000;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_BrowserPlugin_R_H__
