//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AwAutofillClient.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AWAUTOFILLCLIENT_CALLBACK_DEC_HH
#define ELASTOS_AWAUTOFILLCLIENT_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AwAutofillClient_nativeSuggestionSelected(IInterface* caller,Handle64 nativeAwAutofillClient,Int32 position);
    extern void Elastos_AwAutofillClient_InitCallback(Handle64 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace AndroidWebview {

struct ElaAwAutofillClientCallback
{
    AutoPtr<IInterface> (*elastos_AwAutofillClient_create)(Handle64 nativeClient);
    void (*elastos_AwAutofillClient_showAutofillPopup)(IInterface* obj, Float x, Float y, Float width, Float height, ArrayOf<IInterface*>* suggestions);
    void (*elastos_AwAutofillClient_hideAutofillPopup)(IInterface* obj);
    AutoPtr<ArrayOf<IInterface*> > (*elastos_AwAutofillClient_createAutofillSuggestionArray)(Int32 size);
    void (*elastos_AwAutofillClient_addToAutofillSuggestionArray)(ArrayOf<IInterface*>* array, Int32 index, const String& name, const String& label, Int32 uniqueId);
};

void* AwAutofillClient::ElaAwAutofillClientCallback_Init()
{
    static ElaAwAutofillClientCallback sElaAwAutofillClientCallback;

    sElaAwAutofillClientCallback.elastos_AwAutofillClient_create = &AwAutofillClient::Create;
    sElaAwAutofillClientCallback.elastos_AwAutofillClient_showAutofillPopup = &AwAutofillClient::ShowAutofillPopup;
    sElaAwAutofillClientCallback.elastos_AwAutofillClient_hideAutofillPopup = &AwAutofillClient::HideAutofillPopup;
    sElaAwAutofillClientCallback.elastos_AwAutofillClient_createAutofillSuggestionArray = &AwAutofillClient::CreateAutofillSuggestionArray;
    sElaAwAutofillClientCallback.elastos_AwAutofillClient_addToAutofillSuggestionArray = &AwAutofillClient::AddToAutofillSuggestionArray;

    Elastos_AwAutofillClient_InitCallback((Handle64)&sElaAwAutofillClientCallback);
    return &sElaAwAutofillClientCallback;
}

static void* sPElaAwAutofillClientCallback = AwAutofillClient::ElaAwAutofillClientCallback_Init();

} // namespace AndroidWebview
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_AWAUTOFILLCLIENT_CALLBACK_DEC_HH
