//This file is autogenerated for
//    AwContentsClientBridge.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AWCONTENTSCLIENTBRIDGE_CALLBACK_DEC_HH
#define ELASTOS_AWCONTENTSCLIENTBRIDGE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AwContentsClientBridge_nativeProceedSslError(IInterface* caller,Handle32 nativeAwContentsClientBridge,Boolean proceed,Int32 id);
    extern void Elastos_AwContentsClientBridge_nativeProvideClientCertificateResponse(IInterface* caller,Handle32 nativeAwContentsClientBridge,Int32 id,ArrayOf<AutoPtr<ArrayOf<Byte> > >* certChain,IInterface* androidKey);
    extern void Elastos_AwContentsClientBridge_nativeConfirmJsResult(IInterface* caller,Handle32 nativeAwContentsClientBridge,Int32 id,const String& prompt);
    extern void Elastos_AwContentsClientBridge_nativeCancelJsResult(IInterface* caller,Handle32 nativeAwContentsClientBridge,Int32 id);
    extern void Elastos_AwContentsClientBridge_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace AndroidWebview {

struct ElaAwContentsClientBridgeCallback
{
    void (*elastos_AwContentsClientBridge_setNativeContentsClientBridge)(IInterface* obj, Int64 nativeContentsClientBridge);
    Boolean (*elastos_AwContentsClientBridge_allowCertificateError)(IInterface* obj, Int32 certError, ArrayOf<Byte>* derBytes, const String& url, Int32 id);
    void (*elastos_AwContentsClientBridge_selectClientCertificate)(IInterface* obj, Int32 id, ArrayOf<String>* keyTypes, ArrayOf<AutoPtr<ArrayOf<Byte> > >* encodedPrincipals, const String& host, Int32 port);
    void (*elastos_AwContentsClientBridge_handleJsAlert)(IInterface* obj, const String& url, const String& message, Int32 id);
    void (*elastos_AwContentsClientBridge_handleJsConfirm)(IInterface* obj, const String& url, const String& message, Int32 id);
    void (*elastos_AwContentsClientBridge_handleJsPrompt)(IInterface* obj, const String& url, const String& message, const String& defaultValue, Int32 id);
    void (*elastos_AwContentsClientBridge_handleJsBeforeUnload)(IInterface* obj, const String& url, const String& message, Int32 id);
    Boolean (*elastos_AwContentsClientBridge_shouldOverrideUrlLoading)(IInterface* obj, const String& url);
};

void* AwContentsClientBridge::ElaAwContentsClientBridgeCallback_Init()
{
    static ElaAwContentsClientBridgeCallback sElaAwContentsClientBridgeCallback;

    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_setNativeContentsClientBridge = &AwContentsClientBridge::SetNativeContentsClientBridge;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_allowCertificateError = &AwContentsClientBridge::AllowCertificateError;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_selectClientCertificate = &AwContentsClientBridge::SelectClientCertificate;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_handleJsAlert = &AwContentsClientBridge::HandleJsAlert;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_handleJsConfirm = &AwContentsClientBridge::HandleJsConfirm;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_handleJsPrompt = &AwContentsClientBridge::HandleJsPrompt;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_handleJsBeforeUnload = &AwContentsClientBridge::HandleJsBeforeUnload;
    sElaAwContentsClientBridgeCallback.elastos_AwContentsClientBridge_shouldOverrideUrlLoading = &AwContentsClientBridge::ShouldOverrideUrlLoading;

    Elastos_AwContentsClientBridge_InitCallback((Handle32)&sElaAwContentsClientBridgeCallback);
    return &sElaAwContentsClientBridgeCallback;
}

static void* sPElaAwContentsClientBridgeCallback = AwContentsClientBridge::ElaAwContentsClientBridgeCallback_Init();

} // namespace AndroidWebview
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_AWCONTENTSCLIENTBRIDGE_CALLBACK_DEC_HH
