//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AwDevToolsServer.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AWDEVTOOLSSERVER_CALLBACK_DEC_HH
#define ELASTOS_AWDEVTOOLSSERVER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Int64 Elastos_AwDevToolsServer_nativeInitRemoteDebugging(IInterface* caller);
    extern void Elastos_AwDevToolsServer_nativeDestroyRemoteDebugging(IInterface* caller,Int64 devToolsServer);
    extern void Elastos_AwDevToolsServer_nativeSetRemoteDebuggingEnabled(IInterface* caller,Int64 devToolsServer,Boolean enabled);
#ifdef __cplusplus
}
#endif


#endif //ELASTOS_AWDEVTOOLSSERVER_CALLBACK_DEC_HH
