//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AwHttpAuthHandler.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AWHTTPAUTHHANDLER_CALLBACK_DEC_HH
#define ELASTOS_AWHTTPAUTHHANDLER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AwHttpAuthHandler_nativeProceed(IInterface* caller,HANDLE nativeAwHttpAuthHandler,const String& username,const String& password);
    extern void Elastos_AwHttpAuthHandler_nativeCancel(IInterface* caller,HANDLE nativeAwHttpAuthHandler);
    extern void Elastos_AwHttpAuthHandler_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace AndroidWebview {

struct ElaAwHttpAuthHandlerCallback
{
    AutoPtr<IInterface> (*elastos_AwHttpAuthHandler_create)(HANDLE nativeAwAuthHandler, Boolean firstAttempt);
    void (*elastos_AwHttpAuthHandler_handlerDestroyed)(IInterface* obj);
};

void* AwHttpAuthHandler::ElaAwHttpAuthHandlerCallback_Init()
{
    static ElaAwHttpAuthHandlerCallback sElaAwHttpAuthHandlerCallback;

    sElaAwHttpAuthHandlerCallback.elastos_AwHttpAuthHandler_create = &AwHttpAuthHandler::Create;
    sElaAwHttpAuthHandlerCallback.elastos_AwHttpAuthHandler_handlerDestroyed = &AwHttpAuthHandler::HandlerDestroyed;

    Elastos_AwHttpAuthHandler_InitCallback((HANDLE)&sElaAwHttpAuthHandlerCallback);
    return &sElaAwHttpAuthHandlerCallback;
}

static void* sPElaAwHttpAuthHandlerCallback = AwHttpAuthHandler::ElaAwHttpAuthHandlerCallback_Init();

} // namespace AndroidWebview
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_AWHTTPAUTHHANDLER_CALLBACK_DEC_HH
