//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AwResource.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AWRESOURCE_CALLBACK_DEC_HH
#define ELASTOS_AWRESOURCE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AwResource_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace AndroidWebview {

struct ElaAwResourceCallback
{
    String (*elastos_AwResource_getDefaultTextEncoding)();
    String (*elastos_AwResource_getNoDomainPageContent)();
    String (*elastos_AwResource_getLoadErrorPageContent)();
};

void* AwResource::ElaAwResourceCallback_Init()
{
    static ElaAwResourceCallback sElaAwResourceCallback;

    sElaAwResourceCallback.elastos_AwResource_getDefaultTextEncoding = &AwResource::GetDefaultTextEncoding;
    sElaAwResourceCallback.elastos_AwResource_getNoDomainPageContent = &AwResource::GetNoDomainPageContent;
    sElaAwResourceCallback.elastos_AwResource_getLoadErrorPageContent = &AwResource::GetLoadErrorPageContent;

    Elastos_AwResource_InitCallback((Handle32)&sElaAwResourceCallback);
    return &sElaAwResourceCallback;
}

static void* sPElaAwResourceCallback = AwResource::ElaAwResourceCallback_Init();

} // namespace AndroidWebview
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_AWRESOURCE_CALLBACK_DEC_HH
