//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AndroidProtocolHandler.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_ANDROIDPROTOCOLHANDLER_CALLBACK_DEC_HH
#define ELASTOS_ANDROIDPROTOCOLHANDLER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AndroidProtocolHandler_nativeSetResourceContextForTesting(IInterface* context);
    extern String Elastos_AndroidProtocolHandler_nativeGetAndroidAssetPath();
    extern String Elastos_AndroidProtocolHandler_nativeGetAndroidResourcePath();
    extern void Elastos_AndroidProtocolHandler_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace AndroidWebview {

struct ElaAndroidProtocolHandlerCallback
{
    AutoPtr<IInterface> (*elastos_AndroidProtocolHandler_open)(IInterface* context, const String& url);
    String (*elastos_AndroidProtocolHandler_getMimeType)(IInterface* context, IInterface* stream, const String& url);
};

void* ElastosProtocolHandler::ElaElastosProtocolHandlerCallback_Init()
{
    static ElaAndroidProtocolHandlerCallback sElaAndroidProtocolHandlerCallback;

    sElaAndroidProtocolHandlerCallback.elastos_AndroidProtocolHandler_open = &ElastosProtocolHandler::Open;
    sElaAndroidProtocolHandlerCallback.elastos_AndroidProtocolHandler_getMimeType = &ElastosProtocolHandler::GetMimeType;

    Elastos_AndroidProtocolHandler_InitCallback((HANDLE)&sElaAndroidProtocolHandlerCallback);
    return &sElaAndroidProtocolHandlerCallback;
}

static void* sPElaElastosProtocolHandlerCallback = ElastosProtocolHandler::ElaElastosProtocolHandlerCallback_Init();

} // namespace AndroidWebview
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_ANDROIDPROTOCOLHANDLER_CALLBACK_DEC_HH
