//This file is autogenerated for
//    X509Util.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_X509UTIL_CALLBACK_DEC_HH
#define ELASTOS_X509UTIL_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_X509Util_nativeNotifyKeyChainChanged();
    extern void Elastos_X509Util_nativeRecordCertVerifyCapabilitiesHistogram(Boolean foundSystemTrustRoots);
    extern AutoPtr<IInterface> Elastos_X509Util_nativeGetApplicationContext();
#ifdef __cplusplus
}
#endif


#endif //ELASTOS_X509UTIL_CALLBACK_DEC_HH
