/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_ProgressBarDemo_R_H__
#define __Elastos_DevSamples_ProgressBarDemo_R_H__
namespace Elastos {
namespace DevSamples {
namespace ProgressBarDemo {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int test0 = 0x7f020000;
        public: static const int test1 = 0x7f020001;
        public: static const int test10 = 0x7f020002;
        public: static const int test2 = 0x7f020003;
        public: static const int test3 = 0x7f020004;
        public: static const int test4 = 0x7f020005;
        public: static const int test5 = 0x7f020006;
        public: static const int test6 = 0x7f020007;
        public: static const int test7 = 0x7f020008;
        public: static const int test8 = 0x7f020009;
        public: static const int test9 = 0x7f02000a;
    };
    public: class id {
        public: static const int ProgressBar = 0x7f050000;
        public: static const int tabhost = 0x7f050001;
        public: static const int view1 = 0x7f050002;
        public: static const int view2 = 0x7f050003;
        public: static const int view3 = 0x7f050004;
        public: static const int DatePicker = 0x7f050005;
        public: static const int SeekBar = 0x7f050006;
        public: static const int NumberPicker = 0x7f050007;
        public: static const int TimePicker = 0x7f050008;
        public: static const int ViewSwitcher = 0x7f050009;
        public: static const int prev = 0x7f05000a;
        public: static const int next = 0x7f05000b;
        public: static const int ImageSwitcher = 0x7f05000c;
        public: static const int last = 0x7f05000d;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};

#endif // __Elastos_DevSamples_ProgressBarDemo_R_H__
