//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    BrowserStartupController.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_BROWSERSTARTUPCONTROLLER_CALLBACK_DEC_HH
#define ELASTOS_BROWSERSTARTUPCONTROLLER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_BrowserStartupController_nativeSetCommandLineFlags(Int32 maxRenderProcesses,const String& pluginDescriptor);
    extern Boolean Elastos_BrowserStartupController_nativeIsOfficialBuild();
    extern Boolean Elastos_BrowserStartupController_nativeIsPluginEnabled();
    extern void Elastos_BrowserStartupController_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaBrowserStartupControllerCallback
{
    Boolean (*elastos_BrowserStartupController_browserMayStartAsynchonously)();
    void (*elastos_BrowserStartupController_browserStartupComplete)(Int32 result);
};

void* BrowserStartupController::ElaBrowserStartupControllerCallback_Init()
{
    static ElaBrowserStartupControllerCallback sElaBrowserStartupControllerCallback;

    sElaBrowserStartupControllerCallback.elastos_BrowserStartupController_browserMayStartAsynchonously = &BrowserStartupController::BrowserMayStartAsynchonously;
    sElaBrowserStartupControllerCallback.elastos_BrowserStartupController_browserStartupComplete = &BrowserStartupController::BrowserStartupComplete;

    Elastos_BrowserStartupController_InitCallback((HANDLE)&sElaBrowserStartupControllerCallback);
    return &sElaBrowserStartupControllerCallback;
}

static void* sPElaBrowserStartupControllerCallback = BrowserStartupController::ElaBrowserStartupControllerCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_BROWSERSTARTUPCONTROLLER_CALLBACK_DEC_HH
