//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    ContentReadbackHandler.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_CONTENTREADBACKHANDLER_CALLBACK_DEC_HH
#define ELASTOS_CONTENTREADBACKHANDLER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern HANDLE Elastos_ContentReadbackHandler_nativeInit(IInterface* caller);
    extern void Elastos_ContentReadbackHandler_nativeDestroy(IInterface* caller,HANDLE nativeContentReadbackHandler);
    extern void Elastos_ContentReadbackHandler_nativeGetContentBitmap(IInterface* caller,HANDLE nativeContentReadbackHandler,Int32 readback_id,Float scale,Int32 config,Float x,Float y,Float width,Float height,IInterface* contentViewCore);
    extern void Elastos_ContentReadbackHandler_nativeGetCompositorBitmap(IInterface* caller,HANDLE nativeContentReadbackHandler,Int32 readback_id,HANDLE nativeWindowAndroid);
    extern void Elastos_ContentReadbackHandler_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaContentReadbackHandlerCallback
{
    void (*elastos_ContentReadbackHandler_notifyGetBitmapFinished)(IInterface* obj, Int32 readbackId, Boolean success, IInterface* bitmap);
};

void* ContentReadbackHandler::ElaContentReadbackHandlerCallback_Init()
{
    static ElaContentReadbackHandlerCallback sElaContentReadbackHandlerCallback;

    sElaContentReadbackHandlerCallback.elastos_ContentReadbackHandler_notifyGetBitmapFinished = &ContentReadbackHandler::NotifyGetBitmapFinished;

    Elastos_ContentReadbackHandler_InitCallback((HANDLE)&sElaContentReadbackHandlerCallback);
    return &sElaContentReadbackHandlerCallback;
}

static void* sPElaContentReadbackHandlerCallback = ContentReadbackHandler::ElaContentReadbackHandlerCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_CONTENTREADBACKHANDLER_CALLBACK_DEC_HH
