//This file is autogenerated for
//    LoadUrlParams.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_LOADURLPARAMS_CALLBACK_DEC_HH
#define ELASTOS_LOADURLPARAMS_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Boolean Elastos_LoadUrlParams_nativeIsDataScheme(const String& url);
    extern void Elastos_LoadUrlParams_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaLoadUrlParamsCallback
{
    void (*elastos_LoadUrlParams_initializeConstants)(Int32 load_type_default, Int32 load_type_browser_initiated_http_post, Int32 load_type_data, Int32 ua_override_inherit, Int32 ua_override_false, Int32 ua_override_true);
};

void* LoadUrlParams::ElaLoadUrlParamsCallback_Init()
{
    static ElaLoadUrlParamsCallback sElaLoadUrlParamsCallback;

    sElaLoadUrlParamsCallback.elastos_LoadUrlParams_initializeConstants = &LoadUrlParams::InitializeConstants;

    Elastos_LoadUrlParams_InitCallback((Handle32)&sElaLoadUrlParamsCallback);
    return &sElaLoadUrlParamsCallback;
}

static void* sPElaLoadUrlParamsCallback = LoadUrlParams::ElaLoadUrlParamsCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_LOADURLPARAMS_CALLBACK_DEC_HH
