//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    NavigationControllerImpl.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH
#define ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoBack(IInterface* caller,HANDLE nativeNavigationControllerAndroid);
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoForward(IInterface* caller,HANDLE nativeNavigationControllerAndroid);
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoToOffset(IInterface* caller,HANDLE nativeNavigationControllerAndroid,Int32 offset);
    extern void Elastos_NavigationControllerImpl_nativeGoBack(IInterface* caller,HANDLE nativeNavigationControllerAndroid);
    extern void Elastos_NavigationControllerImpl_nativeGoForward(IInterface* caller,HANDLE nativeNavigationControllerAndroid);
    extern void Elastos_NavigationControllerImpl_nativeGoToOffset(IInterface* caller,HANDLE nativeNavigationControllerAndroid,Int32 offset);
    extern void Elastos_NavigationControllerImpl_nativeGoToNavigationIndex(IInterface* caller,HANDLE nativeNavigationControllerAndroid,Int32 index);
    extern void Elastos_NavigationControllerImpl_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {
namespace Framehost {

struct ElaNavigationControllerImplCallback
{
    AutoPtr<IInterface> (*elastos_NavigationControllerImpl_create)(HANDLE nativeNavigationControllerAndroid);
    void (*elastos_NavigationControllerImpl_destroy)(IInterface* obj);
};

void* NavigationControllerImpl::ElaNavigationControllerImplCallback_Init()
{
    static ElaNavigationControllerImplCallback sElaNavigationControllerImplCallback;

    sElaNavigationControllerImplCallback.elastos_NavigationControllerImpl_create = &NavigationControllerImpl::Create;
    sElaNavigationControllerImplCallback.elastos_NavigationControllerImpl_destroy = &NavigationControllerImpl::Destroy;

    Elastos_NavigationControllerImpl_InitCallback((HANDLE)&sElaNavigationControllerImplCallback);
    return &sElaNavigationControllerImplCallback;
}

static void* sPElaNavigationControllerImplCallback = NavigationControllerImpl::ElaNavigationControllerImplCallback_Init();

} // namespace Framehost
} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH
