//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    ScreenOrientationProvider.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_SCREENORIENTATIONPROVIDER_CALLBACK_DEC_HH
#define ELASTOS_SCREENORIENTATIONPROVIDER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_ScreenOrientationProvider_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaScreenOrientationProviderCallback
{
    AutoPtr<IInterface> (*elastos_ScreenOrientationProvider_create)();
    void (*elastos_ScreenOrientationProvider_lockOrientation)(IInterface* obj, Byte orientations);
    void (*elastos_ScreenOrientationProvider_unlockOrientation)(IInterface* obj);
};

void* ScreenOrientationProvider::ElaScreenOrientationProviderCallback_Init()
{
    static ElaScreenOrientationProviderCallback sElaScreenOrientationProviderCallback;

    sElaScreenOrientationProviderCallback.elastos_ScreenOrientationProvider_create = &ScreenOrientationProvider::Create;
    sElaScreenOrientationProviderCallback.elastos_ScreenOrientationProvider_lockOrientation = &ScreenOrientationProvider::LockOrientation;
    sElaScreenOrientationProviderCallback.elastos_ScreenOrientationProvider_unlockOrientation = &ScreenOrientationProvider::UnlockOrientation;

    Elastos_ScreenOrientationProvider_InitCallback((HANDLE)&sElaScreenOrientationProviderCallback);
    return &sElaScreenOrientationProviderCallback;
}

static void* sPElaScreenOrientationProviderCallback = ScreenOrientationProvider::ElaScreenOrientationProviderCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_SCREENORIENTATIONPROVIDER_CALLBACK_DEC_HH
