//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    SpeechRecognition.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH
#define ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_SpeechRecognition_nativeOnAudioStart(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnSoundStart(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnSoundEnd(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnAudioEnd(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionResults(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid,ArrayOf<String>* results,ArrayOf<Float>* scores,Boolean provisional);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionError(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid,Int32 error);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionEnd(IInterface* caller,Handle64 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_InitCallback(Handle64 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaSpeechRecognitionCallback
{
    AutoPtr<IInterface> (*elastos_SpeechRecognition_createSpeechRecognition)(IInterface* context, Handle64 nativeSpeechRecognizerImplAndroid);
    void (*elastos_SpeechRecognition_startRecognition)(IInterface* obj, const String& language, Boolean continuous, Boolean interimResults);
    void (*elastos_SpeechRecognition_abortRecognition)(IInterface* obj);
    void (*elastos_SpeechRecognition_stopRecognition)(IInterface* obj);
};

void* SpeechRecognition::ElaSpeechRecognitionCallback_Init()
{
    static ElaSpeechRecognitionCallback sElaSpeechRecognitionCallback;

    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_createSpeechRecognition = &SpeechRecognition::CreateSpeechRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_startRecognition = &SpeechRecognition::StartRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_abortRecognition = &SpeechRecognition::AbortRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_stopRecognition = &SpeechRecognition::StopRecognition;

    Elastos_SpeechRecognition_InitCallback((Handle64)&sElaSpeechRecognitionCallback);
    return &sElaSpeechRecognitionCallback;
}

static void* sPElaSpeechRecognitionCallback = SpeechRecognition::ElaSpeechRecognitionCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH
