//This file is autogenerated for
//    VibrationProvider.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_VIBRATIONPROVIDER_CALLBACK_DEC_HH
#define ELASTOS_VIBRATIONPROVIDER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_VibrationProvider_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaVibrationProviderCallback
{
    AutoPtr<IInterface> (*elastos_VibrationProvider_create)(IInterface* context);
    void (*elastos_VibrationProvider_vibrate)(IInterface* obj, Int64 milliseconds);
    void (*elastos_VibrationProvider_cancelVibration)(IInterface* obj);
};

void* VibrationProvider::ElaVibrationProviderCallback_Init()
{
    static ElaVibrationProviderCallback sElaVibrationProviderCallback;

    sElaVibrationProviderCallback.elastos_VibrationProvider_create = &VibrationProvider::Create;
    sElaVibrationProviderCallback.elastos_VibrationProvider_vibrate = &VibrationProvider::Vibrate;
    sElaVibrationProviderCallback.elastos_VibrationProvider_cancelVibration = &VibrationProvider::CancelVibration;

    Elastos_VibrationProvider_InitCallback((Handle32)&sElaVibrationProviderCallback);
    return &sElaVibrationProviderCallback;
}

static void* sPElaVibrationProviderCallback = VibrationProvider::ElaVibrationProviderCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_VIBRATIONPROVIDER_CALLBACK_DEC_HH
