#ifndef __ELASTOS_DROID_SYSTEMUI_RECENT_CTASKDESCRIPTION_H__
#define __ELASTOS_DROID_SYSTEMUI_RECENT_CTASKDESCRIPTION_H__

#include "_Elastos_Droid_SystemUI_Recent_CTaskDescription.h"

using Elastos::Core::ICharSequence;
using Elastos::Droid::Content::IIntent;
using Elastos::Droid::Content::Pm::IResolveInfo;
using Elastos::Droid::Graphics::IBitmap;
using Elastos::Droid::Graphics::Drawable::IDrawable;

namespace Elastos {
namespace Droid {
namespace SystemUI {
namespace Recent {

CarClass(CTaskDescription)
{
public:
    CTaskDescription();

    CARAPI constructor();

    CARAPI constructor(
        /* [in] */ Int32 taskId,
        /* [in] */ Int32 persistentTaskId,
        /* [in] */ IResolveInfo* resolveInfo,
        /* [in] */ IIntent* intent,
        /* [in] */ const String& packageName,
        /* [in] */ ICharSequence* description);

    CARAPI SetLoaded(
        /* [in] */ Boolean loaded);

    CARAPI IsLoaded(
        /* [out] */ Boolean* loaded);

    CARAPI IsNull(
        /* [out] */ Boolean* result);

    CARAPI GetLabel(
        /* [out] */ ICharSequence** label);

    CARAPI SetLabel(
        /* [in] */ ICharSequence* label);

    CARAPI GetIcon(
        /* [out] */ IDrawable** drawable);

    CARAPI SetIcon(
        /* [in] */ IDrawable* drawable);

    CARAPI SetThumbnail(
        /* [in] */ IBitmap* bitmap);

    CARAPI GetThumbnail(
        /* [out] */ IBitmap** bitmap);

    CARAPI SetResolveInfo(
        /* [in] */ IResolveInfo* resolveInfo);

    CARAPI GetResolveInfo(
        /* [out] */ IResolveInfo** resolveInfo);

    CARAPI SetTaskId(
        /* [in] */ Int32 taskId);

    CARAPI GetTaskId(
        /* [out] */ Int32* taskId);

    CARAPI SetPersistentTaskId(
        /* [in] */ Int32 persistentTaskId);

    CARAPI GetPersistentTaskId(
        /* [out] */ Int32* persistentTaskId);

    CARAPI SetIntent(
        /* [in] */ IIntent* intent);

    CARAPI GetIntent(
        /* [out] */ IIntent** intent);

    CARAPI SetPackageName(
        /* [in] */ const String& packageName);

    CARAPI GetPackageName(
        /* [out] */ String* packageName);

    CARAPI SetDescription(
        /* [in] */ ICharSequence* description);

    CARAPI GetDescription(
        /* [out] */ ICharSequence** description);

    CARAPI Lock();

    CARAPI Unlock();

public:
    AutoPtr<IResolveInfo> mResolveInfo;
    Int32 mTaskId; // application task id for curating apps
    Int32 mPersistentTaskId; // persistent id
    AutoPtr<IIntent> mIntent; // launch intent for application
    String mPackageName; // used to override animations (see onClick())
    AutoPtr<ICharSequence> mDescription;

private:
    AutoPtr<IBitmap> mThumbnail; // generated by Activity.onCreateThumbnail()
    AutoPtr<IDrawable> mIcon; // application package icon
    AutoPtr<ICharSequence> mLabel; // application package label
    Boolean mLoaded;
};

}// namespace Recent
}// namespace SystemUI
}// namespace Droid
}// namespace Elastos

#endif //__ELASTOS_DROID_SYSTEMUI_RECENT_CTASKDESCRIPTION_H__
