/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_SwitchDemo_R_H__
#define __Elastos_Droid_DevSamples_SwitchDemo_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace SwitchDemo {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int earth = 0x7f020000;
        public: static const int icon = 0x7f020001;
    };
    public: class id {
        public: static const int textview = 0x7f050000;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_SwitchDemo_R_H__
