/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_PopupMenuDemo_R_H__
#define __Elastos_DevSamples_PopupMenuDemo_R_H__

#include <elatypes.h>

namespace Elastos {
namespace DevSamples {
namespace PopupMenuDemo {

class ECO_PUBLIC R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int button = 0x7f060000;
        public: static const int help = 0x7f060002;
        public: static const int new_game = 0x7f060001;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class menu {
        public: static const int action = 0x7f050000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
        public: static const int hello = 0x7f040001;
        public: static const int planet_prompt = 0x7f040002;
    };

};
};
};
};
#endif // __Elastos_DevSamples_PopupMenuDemo_R_H__
