//This file is autogenerated for
//    AudioManagerAndroid.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_AUDIOMANAGERANDROID_CALLBACK_DEC_HH
#define ELASTOS_AUDIOMANAGERANDROID_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AudioManagerAndroid_nativeSetMute(IInterface* caller,Handle32 nativeAudioManagerAndroid,Boolean muted);
    extern void Elastos_AudioManagerAndroid_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Media {

struct ElaAudioManagerAndroidCallback
{
    Elastos::String (*elastos_AudioDeviceName_id)(IInterface* obj);
    Elastos::String (*elastos_AudioDeviceName_name)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_AudioManagerAndroid_createAudioManagerAndroid)(IInterface* context, Int64 nativeAudioManagerAndroid);
    void (*elastos_AudioManagerAndroid_init)(IInterface* obj);
    void (*elastos_AudioManagerAndroid_close)(IInterface* obj);
    void (*elastos_AudioManagerAndroid_setCommunicationAudioModeOn)(IInterface* obj, Boolean on);
    Boolean (*elastos_AudioManagerAndroid_setDevice)(IInterface* obj, const Elastos::String& deviceId);
    AutoPtr<ArrayOf<IInterface*> > (*elastos_AudioManagerAndroid_getAudioInputDeviceNames)(IInterface* obj);
    Int32 (*elastos_AudioManagerAndroid_getNativeOutputSampleRate)(IInterface* obj);
    Int32 (*elastos_AudioManagerAndroid_getMinInputFrameSize)(Int32 sampleRate, Int32 channels);
    Int32 (*elastos_AudioManagerAndroid_getMinOutputFrameSize)(Int32 sampleRate, Int32 channels);
    Boolean (*elastos_AudioManagerAndroid_isAudioLowLatencySupported)(IInterface* obj);
    Int32 (*elastos_AudioManagerAndroid_getAudioLowLatencyOutputFrameSize)(IInterface* obj);
    Boolean (*elastos_AudioManagerAndroid_shouldUseAcousticEchoCanceler)();
};

void* AudioManagerElastos::ElaAudioManagerElastosCallback_Init()
{
    static ElaAudioManagerAndroidCallback sElaAudioManagerAndroidCallback;
    sElaAudioManagerAndroidCallback.elastos_AudioDeviceName_id = &AudioManagerElastos::AudioDeviceName::Id;
    sElaAudioManagerAndroidCallback.elastos_AudioDeviceName_name = &AudioManagerElastos::AudioDeviceName::Name;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_createAudioManagerAndroid = &AudioManagerElastos::CreateAudioManagerElastos;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_init = &AudioManagerElastos::Init;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_close = &AudioManagerElastos::Close;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_setCommunicationAudioModeOn = &AudioManagerElastos::SetCommunicationAudioModeOn;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_setDevice = &AudioManagerElastos::SetDevice;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_getAudioInputDeviceNames = &AudioManagerElastos::GetAudioInputDeviceNames;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_getNativeOutputSampleRate = &AudioManagerElastos::GetNativeOutputSampleRate;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_getMinInputFrameSize = &AudioManagerElastos::GetMinInputFrameSize;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_getMinOutputFrameSize = &AudioManagerElastos::GetMinOutputFrameSize;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_isAudioLowLatencySupported = &AudioManagerElastos::IsAudioLowLatencySupported;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_getAudioLowLatencyOutputFrameSize = &AudioManagerElastos::GetAudioLowLatencyOutputFrameSize;
    sElaAudioManagerAndroidCallback.elastos_AudioManagerAndroid_shouldUseAcousticEchoCanceler = &AudioManagerElastos::ShouldUseAcousticEchoCanceler;

    Elastos_AudioManagerAndroid_InitCallback((Handle32)&sElaAudioManagerAndroidCallback);
    return &sElaAudioManagerAndroidCallback;
}

static void* sPElaAudioManagerAndroidCallback = AudioManagerElastos::ElaAudioManagerElastosCallback_Init();

} // namespace Media
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_AUDIOMANAGERANDROID_CALLBACK_DEC_HH
