//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

#ifndef __ELASTOS_SQL_SQLITE_JDBC_CJDBCCONNECTION_H__
#define __ELASTOS_SQL_SQLITE_JDBC_CJDBCCONNECTION_H__

#include "_Elastos_Sql_SQLite_JDBC_CJDBCConnection.h"
#include "Object.h"

using Elastos::Core::Object;
using Elastos::IO::ICloseable;
using Elastos::Sql::ISQLWarning;
using Elastos::Sql::IStatement;
using Elastos::Sql::IDatabaseMetaData;
using Elastos::Sql::ICallableStatement;
using Elastos::Sql::IPreparedStatement;
using Elastos::Sql::ISavePoint;
using Elastos::Sql::IClob;
using Elastos::Sql::IBlob;
using Elastos::Sql::INClob;
using Elastos::Sql::ISQLXML;
using Elastos::Sql::IPreparedStatement;
using Elastos::Utility::IMap;
using Elastos::Utility::IProperties;

namespace Elastos {
namespace Sql {
namespace SQLite {
namespace JDBC{

CarClass(CJDBCConnection)
    , public Object
    , public IJDBCConnection
    , public IConnection
    , public IWrapper
    , public IBusyHandler
    , public ICloseable
{
public:
    CAR_OBJECT_DECL()

    CAR_INTERFACE_DECL()

    CARAPI ClearWarnings();

    CARAPI Close();

    CARAPI Commit();

    CARAPI CreateStatement(
        /* [out] */ IStatement ** ppStatement);

    CARAPI CreateStatement(
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [out] */ IStatement ** ppStatement);

    CARAPI CreateStatement(
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [in] */ Int32 resultSetHoldability,
        /* [out] */ IStatement ** ppStatement);

    CARAPI GetAutoCommit(
        /* [out] */ Boolean * pAuto);

    CARAPI GetCatalog(
        /* [out] */ String * pCatelog);

    CARAPI GetHoldability(
        /* [out] */ Int32 * pHoldability);

    CARAPI GetMetaData(
        /* [out] */ IDatabaseMetaData ** ppMetadata);

    CARAPI GetTransactionIsolation(
        /* [out] */ Int32 * pValue);

    CARAPI GetTypeMap(
        /* [out] */ IMap ** typemap);

    CARAPI GetWarnings(
        /* [out] */ ISQLWarning ** ppWarning);

    CARAPI IsClosed(
        /* [out] */ Boolean * pIsClosed);

    CARAPI IsReadOnly(
        /* [out] */ Boolean * pIsReadOnly);

    CARAPI NativeSQL(
        /* [in] */ const String& sql,
        /* [out] */ String * pNsql);

    CARAPI PrepareCall(
        /* [in] */ const String& sql,
        /* [out] */ ICallableStatement ** ppCallableStatement);

    CARAPI PrepareCall(
        /* [in] */ const String& sql,
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [out] */ ICallableStatement ** ppCallableStatement);

    CARAPI PrepareCall(
        /* [in] */ const String& sql,
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [in] */ Int32 resultSetHoldability,
        /* [out] */ ICallableStatement ** ppCallableStatement);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [out] */ IPreparedStatement ** ppPreparedStatement);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [in] */ Int32 autoGeneratedKeys,
        /* [out] */ IPreparedStatement ** ppPreparedStatement);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [in] */ const ArrayOf<Int32> & columnIndexes,
        /* [out] */ IPreparedStatement ** ppPreparedStatement);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [out] */ IPreparedStatement ** ppStatement);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [in] */ Int32 resultSetType,
        /* [in] */ Int32 resultSetConcurrency,
        /* [in] */ Int32 resultSetHoldability,
        /* [out] */ IPreparedStatement ** ppPreparedStatement);

    CARAPI ReleaseSavepoint(
        /* [in] */ ISavePoint * pSavepoint);

    CARAPI Rollback();

    CARAPI Rollback(
        /* [in] */ ISavePoint * pSavepoint);

    CARAPI SetAutoCommit(
        /* [in] */ Boolean autoCommit);

    CARAPI SetCatalog(
        /* [in] */ const String& catalog);

    CARAPI SetHoldability(
        /* [in] */ Int32 holdability);

    CARAPI SetReadOnly(
        /* [in] */ Boolean readOnly);

    CARAPI SetSavepoint(
        /* [out] */ ISavePoint ** ppSavepoint);

    CARAPI SetSavepoint(
        /* [in] */ const String& name,
        /* [out] */ ISavePoint ** ppSavepoint);

    CARAPI SetTransactionIsolation(
        /* [in] */ Int32 level);

    CARAPI SetTypeMap(
        /* [in] */ IMap * typemap);

    CARAPI CreateClob(
        /* [out] */ IClob ** ppClob);

    CARAPI CreateBlob(
        /* [out] */ Elastos::Sql::IBlob ** ppBlob);

    CARAPI CreateNClob(
        /* [out] */ INClob ** ppNclob);

    CARAPI CreateSQLXML(
        /* [out] */ ISQLXML ** ppSqlXML);

    CARAPI IsValid(
        /* [in] */ Int32 timeout,
        /* [out] */ Boolean * pValid);

    CARAPI SetClientInfo(
        /* [in] */ const String& name,
        /* [in] */ const String& value);

    CARAPI GetClientInfo(
        /* [out] */ IProperties** properties);

    CARAPI Busy(
        /* [in] */ const String& table,
        /* [in] */ Int32 count,
        /* [out] */ Boolean * pValue);

    CARAPI constructor(
        /* [in] */ const String& url,
        /* [in] */ const String& enc,
        /* [in] */ const String& pwd,
        /* [in] */ const String& drep,
        /* [in] */ const String& vfs);

    CARAPI GetSQLiteDatabase(
        /* [out] */ IDatabase** ppDb);

    CARAPI PrepareStatement(
        /* [in] */ const String& sql,
        /* [in] */ const ArrayOf<String>& columnNames,
        /* [out] */ IPreparedStatement** preparedStatement);

    CARAPI GetClientInfo(
        /* [in] */ const String& name,
        /* [out] */ String* info);

    CARAPI IsWrapperFor(
        /* [in] */ IInterface * iface,
        /* [out] */ Boolean * value);

    CARAPI SetClientInfo(
        /* [in] */ IProperties* properties);
    CARAPI CreateArrayOf(
        /* [in] */ const String& typeName,
        /* [in] */ const ArrayOf<IInterface * >& elements,
        /* [out] */ IArray ** iarray);

    CARAPI CreateStruct(
        /* [in] */ const String& typeName,
        /* [in] */ const ArrayOf<IInterface * >& attributes,
        /* [out] */ IStruct ** istruct);

    CARAPI Unwrap(
        /* [in] */ PInterface iface,
        /* [out] */ IInterface ** oface);

    CARAPI_(Boolean) Busy3(
        /* [in] */ IDatabase* db,
        /* [in] */ Int32 count);

private:
    ECode Busy0(
        /* [in] */ IDatabase* db,
        /* [in] */ Int32 count,
        /* [out] */ Boolean* value);

    ECode Open(
        /* [in] */ Boolean readonly,
        /* [out] */ IDatabase** db);

public:
    AutoPtr<IDatabase> mDb;
    Int64 timeout;
    String mVfs;
    String mEnc;
    Boolean mUseJulian;
    String mUrl;
    Boolean mIntrans;
    Boolean mAutocommit;

private:
    Int64 mT0;
    String mDbfile;
    Boolean mReadonly;
    Int32 mTrmode;
};

} // namespace JDBC
} // namespace SQLite
} // namespace Sql
} // namespace Elastos

#endif // __ELASTOS_SQL_SQLITE_JDBC_CJDBCCONNECTION_H__
