//This file is autogenerated for
//    NavigationControllerImpl.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH
#define ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoBack(IInterface* caller,Handle32 nativeNavigationControllerAndroid);
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoForward(IInterface* caller,Handle32 nativeNavigationControllerAndroid);
    extern Boolean Elastos_NavigationControllerImpl_nativeCanGoToOffset(IInterface* caller,Handle32 nativeNavigationControllerAndroid,Int32 offset);
    extern void Elastos_NavigationControllerImpl_nativeGoBack(IInterface* caller,Handle32 nativeNavigationControllerAndroid);
    extern void Elastos_NavigationControllerImpl_nativeGoForward(IInterface* caller,Handle32 nativeNavigationControllerAndroid);
    extern void Elastos_NavigationControllerImpl_nativeGoToOffset(IInterface* caller,Handle32 nativeNavigationControllerAndroid,Int32 offset);
    extern void Elastos_NavigationControllerImpl_nativeGoToNavigationIndex(IInterface* caller,Handle32 nativeNavigationControllerAndroid,Int32 index);
    extern void Elastos_NavigationControllerImpl_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {
namespace Framehost {

struct ElaNavigationControllerImplCallback
{
    AutoPtr<IInterface> (*elastos_NavigationControllerImpl_create)(Int64 nativeNavigationControllerAndroid);
    void (*elastos_NavigationControllerImpl_destroy)(IInterface* obj);
};

void* NavigationControllerImpl::ElaNavigationControllerImplCallback_Init()
{
    static ElaNavigationControllerImplCallback sElaNavigationControllerImplCallback;

    sElaNavigationControllerImplCallback.elastos_NavigationControllerImpl_create = &NavigationControllerImpl::Create;
    sElaNavigationControllerImplCallback.elastos_NavigationControllerImpl_destroy = &NavigationControllerImpl::Destroy;

    Elastos_NavigationControllerImpl_InitCallback((Handle32)&sElaNavigationControllerImplCallback);
    return &sElaNavigationControllerImplCallback;
}

static void* sPElaNavigationControllerImplCallback = NavigationControllerImpl::ElaNavigationControllerImplCallback_Init();

} // namespace Framehost
} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_NAVIGATIONCONTROLLERIMPL_CALLBACK_DEC_HH
