//This file is autogenerated for
//    SpeechRecognition.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH
#define ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_SpeechRecognition_nativeOnAudioStart(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnSoundStart(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnSoundEnd(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnAudioEnd(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionResults(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid,ArrayOf<String>* results,ArrayOf<Float>* scores,Boolean provisional);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionError(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid,Int32 error);
    extern void Elastos_SpeechRecognition_nativeOnRecognitionEnd(IInterface* caller,Handle32 nativeSpeechRecognizerImplAndroid);
    extern void Elastos_SpeechRecognition_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {

struct ElaSpeechRecognitionCallback
{
    AutoPtr<IInterface> (*elastos_SpeechRecognition_createSpeechRecognition)(IInterface* context, Int64 nativeSpeechRecognizerImplAndroid);
    void (*elastos_SpeechRecognition_startRecognition)(IInterface* obj, const String& language, Boolean continuous, Boolean interimResults);
    void (*elastos_SpeechRecognition_abortRecognition)(IInterface* obj);
    void (*elastos_SpeechRecognition_stopRecognition)(IInterface* obj);
};

void* SpeechRecognition::ElaSpeechRecognitionCallback_Init()
{
    static ElaSpeechRecognitionCallback sElaSpeechRecognitionCallback;

    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_createSpeechRecognition = &SpeechRecognition::CreateSpeechRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_startRecognition = &SpeechRecognition::StartRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_abortRecognition = &SpeechRecognition::AbortRecognition;
    sElaSpeechRecognitionCallback.elastos_SpeechRecognition_stopRecognition = &SpeechRecognition::StopRecognition;

    Elastos_SpeechRecognition_InitCallback((Handle32)&sElaSpeechRecognitionCallback);
    return &sElaSpeechRecognitionCallback;
}

static void* sPElaSpeechRecognitionCallback = SpeechRecognition::ElaSpeechRecognitionCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_SPEECHRECOGNITION_CALLBACK_DEC_HH
