/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_SavingData_R_H__
#define __Elastos_Droid_DevSamples_SavingData_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace SavingData {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int adddata = 0x7f050005;
        public: static const int dataid = 0x7f050000;
        public: static const int datatitle = 0x7f050001;
        public: static const int deldata = 0x7f050006;
        public: static const int externaltext = 0x7f050004;
        public: static const int internaltext = 0x7f050003;
        public: static const int sharedtext = 0x7f050002;
        public: static const int sqlListView = 0x7f050007;
    };
    public: class layout {
        public: static const int list_item = 0x7f030000;
        public: static const int main = 0x7f030001;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
        public: static const int key = 0x7f040003;
        public: static const int only = 0x7f040002;
        public: static const int shared = 0x7f040001;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_SavingData_R_H__
