//This file is autogenerated for
//    NavigationParams.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_NAVIGATIONPARAMS_CALLBACK_DEC_HH
#define ELASTOS_NAVIGATIONPARAMS_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_NavigationParams_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Components {

struct ElaNavigationParamsCallback
{
    AutoPtr<IInterface> (*elastos_NavigationParams_create)(const String& url, Boolean isPost, Boolean hasUserGesture, Int32 pageTransitionType, Boolean isRedirect);
};

void* NavigationParams::ElaNavigationParamsCallback_Init()
{
    static ElaNavigationParamsCallback sElaNavigationParamsCallback;

    sElaNavigationParamsCallback.elastos_NavigationParams_create = &NavigationParams::Create;

    Elastos_NavigationParams_InitCallback((Handle32)&sElaNavigationParamsCallback);
    return &sElaNavigationParamsCallback;
}

static void* sPElaNavigationParamsCallback = NavigationParams::ElaNavigationParamsCallback_Init();

} // namespace Components
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_NAVIGATIONPARAMS_CALLBACK_DEC_HH
