//This file is autogenerated for
//    PersonalAutofillPopulator.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_PERSONALAUTOFILLPOPULATOR_CALLBACK_DEC_HH
#define ELASTOS_PERSONALAUTOFILLPOPULATOR_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_PersonalAutofillPopulator_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Components {

struct ElaPersonalAutofillPopulatorCallback
{
    AutoPtr<IInterface> (*elastos_PersonalAutofillPopulator_create)(IInterface* context);
    String (*elastos_PersonalAutofillPopulator_getFirstName)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getLastName)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getMiddleName)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getSuffix)(IInterface* obj);
    AutoPtr<ArrayOf<String> > (*elastos_PersonalAutofillPopulator_getEmailAddresses)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getStreet)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getPobox)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getNeighborhood)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getCity)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getRegion)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getPostalCode)(IInterface* obj);
    String (*elastos_PersonalAutofillPopulator_getCountry)(IInterface* obj);
    AutoPtr<ArrayOf<String> > (*elastos_PersonalAutofillPopulator_getPhoneNumbers)(IInterface* obj);
    Boolean (*elastos_PersonalAutofillPopulator_getHasPermissions)(IInterface* obj);
};

void* PersonalAutofillPopulator::ElaPersonalAutofillPopulatorCallback_Init()
{
    static ElaPersonalAutofillPopulatorCallback sElaPersonalAutofillPopulatorCallback;

    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_create = &PersonalAutofillPopulator::Create;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getFirstName = &PersonalAutofillPopulator::GetFirstName;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getLastName = &PersonalAutofillPopulator::GetLastName;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getMiddleName = &PersonalAutofillPopulator::GetMiddleName;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getSuffix = &PersonalAutofillPopulator::GetSuffix;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getEmailAddresses = &PersonalAutofillPopulator::GetEmailAddresses;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getStreet = &PersonalAutofillPopulator::GetStreet;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getPobox = &PersonalAutofillPopulator::GetPobox;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getNeighborhood = &PersonalAutofillPopulator::GetNeighborhood;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getCity = &PersonalAutofillPopulator::GetCity;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getRegion = &PersonalAutofillPopulator::GetRegion;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getPostalCode = &PersonalAutofillPopulator::GetPostalCode;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getCountry = &PersonalAutofillPopulator::GetCountry;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getPhoneNumbers = &PersonalAutofillPopulator::GetPhoneNumbers;
    sElaPersonalAutofillPopulatorCallback.elastos_PersonalAutofillPopulator_getHasPermissions = &PersonalAutofillPopulator::GetHasPermissions;

    Elastos_PersonalAutofillPopulator_InitCallback((Handle32)&sElaPersonalAutofillPopulatorCallback);
    return &sElaPersonalAutofillPopulatorCallback;
}

static void* sPElaPersonalAutofillPopulatorCallback = PersonalAutofillPopulator::ElaPersonalAutofillPopulatorCallback_Init();

} // namespace Components
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_PERSONALAUTOFILLPOPULATOR_CALLBACK_DEC_HH
