//This file is autogenerated for
//    ValidationMessageBubble.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_VALIDATIONMESSAGEBUBBLE_CALLBACK_DEC_HH
#define ELASTOS_VALIDATIONMESSAGEBUBBLE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_ValidationMessageBubble_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Components {

struct ElaValidationMessageBubbleCallback
{
    AutoPtr<IInterface> (*elastos_ValidationMessageBubble_createAndShow)(IInterface* contentViewCore, Int32 anchorX, Int32 anchorY, Int32 anchorWidth, Int32 anchorHeight, const String& mainText, const String& subText);
    void (*elastos_ValidationMessageBubble_close)(IInterface* obj);
    void (*elastos_ValidationMessageBubble_setPositionRelativeToAnchor)(IInterface* obj, IInterface* contentViewCore, Int32 anchorX, Int32 anchorY, Int32 anchorWidth, Int32 anchorHeight);
};

void* ValidationMessageBubble::ElaValidationMessageBubbleCallback_Init()
{
    static ElaValidationMessageBubbleCallback sElaValidationMessageBubbleCallback;

    sElaValidationMessageBubbleCallback.elastos_ValidationMessageBubble_createAndShow = &ValidationMessageBubble::CreateAndShow;
    sElaValidationMessageBubbleCallback.elastos_ValidationMessageBubble_close = &ValidationMessageBubble::Close;
    sElaValidationMessageBubbleCallback.elastos_ValidationMessageBubble_setPositionRelativeToAnchor = &ValidationMessageBubble::SetPositionRelativeToAnchor;

    Elastos_ValidationMessageBubble_InitCallback((Handle32)&sElaValidationMessageBubbleCallback);
    return &sElaValidationMessageBubbleCallback;
}

static void* sPElaValidationMessageBubbleCallback = ValidationMessageBubble::ElaValidationMessageBubbleCallback_Init();

} // namespace Components
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_VALIDATIONMESSAGEBUBBLE_CALLBACK_DEC_HH
