//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    MotionEvent.class
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH
#define ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_MotionEvent_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Api {

struct ElaMotionEventCallback
{
    void (*elastos_MotionEvent_finalize)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, ArrayOf<IInterface*>* p4, ArrayOf<IInterface*>* p5, Int32 p6, Int32 p7, Float p8, Float p9, Int32 p10, Int32 p11, Int32 p12, Int32 p13);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, ArrayOf<Int32>* p4, ArrayOf<IInterface*>* p5, Int32 p6, Float p7, Float p8, Int32 p9, Int32 p10, Int32 p11, Int32 p12);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_F_F_F_F_I_F_F_I_I)(Int64 p0, Int64 p1, Int32 p2, Float p3, Float p4, Float p5, Float p6, Int32 p7, Float p8, Float p9, Int32 p10, Int32 p11);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_F_F_F_F_I_F_F_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, Float p4, Float p5, Float p6, Float p7, Int32 p8, Float p9, Float p10, Int32 p11, Int32 p12);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_F_F_I)(Int64 p0, Int64 p1, Int32 p2, Float p3, Float p4, Int32 p5);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_AVME)(IInterface* p0);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainNoHistory)(IInterface* p0);
    void (*elastos_MotionEvent_recycle)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getDeviceId)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getSource)(IInterface* obj);
    void (*elastos_MotionEvent_setSource)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getAction)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getActionMasked)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getActionIndex)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getFlags)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getDownTime)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getEventTime)(IInterface* obj);
    Float (*elastos_MotionEvent_getXF)(IInterface* obj);
    Float (*elastos_MotionEvent_getYF)(IInterface* obj);
    Float (*elastos_MotionEvent_getPressureF)(IInterface* obj);
    Float (*elastos_MotionEvent_getSizeF)(IInterface* obj);
    Float (*elastos_MotionEvent_getTouchMajorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getTouchMinorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getToolMajorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getToolMinorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getOrientationF)(IInterface* obj);
    Float (*elastos_MotionEvent_getAxisValueF_I)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getPointerCount)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getPointerId)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getToolType)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_findPointerIndex)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getXF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getYF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getPressureF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getSizeF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getTouchMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getTouchMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getToolMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getToolMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getOrientationF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getAxisValueF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    void (*elastos_MotionEvent_getPointerCoords)(IInterface* obj, Int32 p0, IInterface* p1);
    void (*elastos_MotionEvent_getPointerProperties)(IInterface* obj, Int32 p0, IInterface* p1);
    Int32 (*elastos_MotionEvent_getMetaState)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getButtonState)(IInterface* obj);
    Float (*elastos_MotionEvent_getRawX)(IInterface* obj);
    Float (*elastos_MotionEvent_getRawY)(IInterface* obj);
    Float (*elastos_MotionEvent_getXPrecision)(IInterface* obj);
    Float (*elastos_MotionEvent_getYPrecision)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getHistorySize)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getHistoricalEventTime)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalXF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalYF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalPressureF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalSizeF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalTouchMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalTouchMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalToolMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalToolMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalOrientationF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalAxisValueF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalXF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalYF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalPressureF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalSizeF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalTouchMajorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalTouchMinorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalToolMajorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalToolMinorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalOrientationF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalAxisValueF_I_I_I)(IInterface* obj, Int32 p0, Int32 p1, Int32 p2);
    void (*elastos_MotionEvent_getHistoricalPointerCoords)(IInterface* obj, Int32 p0, Int32 p1, IInterface* p2);
    Int32 (*elastos_MotionEvent_getEdgeFlags)(IInterface* obj);
    void (*elastos_MotionEvent_setEdgeFlags)(IInterface* obj, Int32 p0);
    void (*elastos_MotionEvent_setAction)(IInterface* obj, Int32 p0);
    void (*elastos_MotionEvent_offsetLocation)(IInterface* obj, Float p0, Float p1);
    void (*elastos_MotionEvent_setLocation)(IInterface* obj, Float p0, Float p1);
    void (*elastos_MotionEvent_transform)(IInterface* obj, IInterface* p0);
    void (*elastos_MotionEvent_addBatchV_J_F_F_F_F_I)(IInterface* obj, Int64 p0, Float p1, Float p2, Float p3, Float p4, Int32 p5);
    void (*elastos_MotionEvent_addBatchV_J_LAVMEPC_I)(IInterface* obj, Int64 p0, ArrayOf<IInterface*>* p1, Int32 p2);
    String (*elastos_MotionEvent_toString)(IInterface* obj);
    String (*elastos_MotionEvent_axisToString)(Int32 p0);
    Int32 (*elastos_MotionEvent_axisFromString)(const String& p0);
    void (*elastos_MotionEvent_writeToParcel)(IInterface* obj, IInterface* p0, Int32 p1);
};

void* AwMotionEvent::ElaMotionEventCallback_Init()
{
    static ElaMotionEventCallback sElaMotionEventCallback;

    sElaMotionEventCallback.elastos_MotionEvent_finalize = &AwMotionEvent::Finalize;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I_I = &AwMotionEvent::ObtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I_I = &AwMotionEvent::ObtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_F_F_F_F_I_F_F_I_I = &AwMotionEvent::ObtainAVME_J_J_I_F_F_F_F_I_F_F_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_F_F_F_F_I_F_F_I_I = &AwMotionEvent::ObtainAVME_J_J_I_I_F_F_F_F_I_F_F_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_F_F_I = &AwMotionEvent::ObtainAVME_J_J_I_F_F_I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_AVME = &AwMotionEvent::ObtainAVME_AVME;
    sElaMotionEventCallback.elastos_MotionEvent_obtainNoHistory = &AwMotionEvent::ObtainNoHistory;
    sElaMotionEventCallback.elastos_MotionEvent_recycle = &AwMotionEvent::Recycle;
    sElaMotionEventCallback.elastos_MotionEvent_getDeviceId = &AwMotionEvent::GetDeviceId;
    sElaMotionEventCallback.elastos_MotionEvent_getSource = &AwMotionEvent::GetSource;
    sElaMotionEventCallback.elastos_MotionEvent_setSource = &AwMotionEvent::SetSource;
    sElaMotionEventCallback.elastos_MotionEvent_getAction = &AwMotionEvent::GetAction;
    sElaMotionEventCallback.elastos_MotionEvent_getActionMasked = &AwMotionEvent::GetActionMasked;
    sElaMotionEventCallback.elastos_MotionEvent_getActionIndex = &AwMotionEvent::GetActionIndex;
    sElaMotionEventCallback.elastos_MotionEvent_getFlags = &AwMotionEvent::GetFlags;
    sElaMotionEventCallback.elastos_MotionEvent_getDownTime = &AwMotionEvent::GetDownTime;
    sElaMotionEventCallback.elastos_MotionEvent_getEventTime = &AwMotionEvent::GetEventTime;
    sElaMotionEventCallback.elastos_MotionEvent_getXF = &AwMotionEvent::GetXF;
    sElaMotionEventCallback.elastos_MotionEvent_getYF = &AwMotionEvent::GetYF;
    sElaMotionEventCallback.elastos_MotionEvent_getPressureF = &AwMotionEvent::GetPressureF;
    sElaMotionEventCallback.elastos_MotionEvent_getSizeF = &AwMotionEvent::GetSizeF;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMajorF = &AwMotionEvent::GetTouchMajorF;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMinorF = &AwMotionEvent::GetTouchMinorF;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMajorF = &AwMotionEvent::GetToolMajorF;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMinorF = &AwMotionEvent::GetToolMinorF;
    sElaMotionEventCallback.elastos_MotionEvent_getOrientationF = &AwMotionEvent::GetOrientationF;
    sElaMotionEventCallback.elastos_MotionEvent_getAxisValueF_I = &AwMotionEvent::GetAxisValueF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerCount = &AwMotionEvent::GetPointerCount;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerId = &AwMotionEvent::GetPointerId;
    sElaMotionEventCallback.elastos_MotionEvent_getToolType = &AwMotionEvent::GetToolType;
    sElaMotionEventCallback.elastos_MotionEvent_findPointerIndex = &AwMotionEvent::FindPointerIndex;
    sElaMotionEventCallback.elastos_MotionEvent_getXF_I = &AwMotionEvent::GetXF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getYF_I = &AwMotionEvent::GetYF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getPressureF_I = &AwMotionEvent::GetPressureF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getSizeF_I = &AwMotionEvent::GetSizeF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMajorF_I = &AwMotionEvent::GetTouchMajorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMinorF_I = &AwMotionEvent::GetTouchMinorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMajorF_I = &AwMotionEvent::GetToolMajorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMinorF_I = &AwMotionEvent::GetToolMinorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getOrientationF_I = &AwMotionEvent::GetOrientationF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getAxisValueF_I_I = &AwMotionEvent::GetAxisValueF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerCoords = &AwMotionEvent::GetPointerCoords;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerProperties = &AwMotionEvent::GetPointerProperties;
    sElaMotionEventCallback.elastos_MotionEvent_getMetaState = &AwMotionEvent::GetMetaState;
    sElaMotionEventCallback.elastos_MotionEvent_getButtonState = &AwMotionEvent::GetButtonState;
    sElaMotionEventCallback.elastos_MotionEvent_getRawX = &AwMotionEvent::GetRawX;
    sElaMotionEventCallback.elastos_MotionEvent_getRawY = &AwMotionEvent::GetRawY;
    sElaMotionEventCallback.elastos_MotionEvent_getXPrecision = &AwMotionEvent::GetXPrecision;
    sElaMotionEventCallback.elastos_MotionEvent_getYPrecision = &AwMotionEvent::GetYPrecision;
    sElaMotionEventCallback.elastos_MotionEvent_getHistorySize = &AwMotionEvent::GetHistorySize;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalEventTime = &AwMotionEvent::GetHistoricalEventTime;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalXF_I = &AwMotionEvent::GetHistoricalXF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalYF_I = &AwMotionEvent::GetHistoricalYF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPressureF_I = &AwMotionEvent::GetHistoricalPressureF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalSizeF_I = &AwMotionEvent::GetHistoricalSizeF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMajorF_I = &AwMotionEvent::GetHistoricalTouchMajorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMinorF_I = &AwMotionEvent::GetHistoricalTouchMinorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMajorF_I = &AwMotionEvent::GetHistoricalToolMajorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMinorF_I = &AwMotionEvent::GetHistoricalToolMinorF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalOrientationF_I = &AwMotionEvent::GetHistoricalOrientationF_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalAxisValueF_I_I = &AwMotionEvent::GetHistoricalAxisValueF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalXF_I_I = &AwMotionEvent::GetHistoricalXF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalYF_I_I = &AwMotionEvent::GetHistoricalYF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPressureF_I_I = &AwMotionEvent::GetHistoricalPressureF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalSizeF_I_I = &AwMotionEvent::GetHistoricalSizeF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMajorF_I_I = &AwMotionEvent::GetHistoricalTouchMajorF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMinorF_I_I = &AwMotionEvent::GetHistoricalTouchMinorF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMajorF_I_I = &AwMotionEvent::GetHistoricalToolMajorF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMinorF_I_I = &AwMotionEvent::GetHistoricalToolMinorF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalOrientationF_I_I = &AwMotionEvent::GetHistoricalOrientationF_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalAxisValueF_I_I_I = &AwMotionEvent::GetHistoricalAxisValueF_I_I_I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPointerCoords = &AwMotionEvent::GetHistoricalPointerCoords;
    sElaMotionEventCallback.elastos_MotionEvent_getEdgeFlags = &AwMotionEvent::GetEdgeFlags;
    sElaMotionEventCallback.elastos_MotionEvent_setEdgeFlags = &AwMotionEvent::SetEdgeFlags;
    sElaMotionEventCallback.elastos_MotionEvent_setAction = &AwMotionEvent::SetAction;
    sElaMotionEventCallback.elastos_MotionEvent_offsetLocation = &AwMotionEvent::OffsetLocation;
    sElaMotionEventCallback.elastos_MotionEvent_setLocation = &AwMotionEvent::SetLocation;
    sElaMotionEventCallback.elastos_MotionEvent_transform = &AwMotionEvent::Transform;
    sElaMotionEventCallback.elastos_MotionEvent_addBatchV_J_F_F_F_F_I = &AwMotionEvent::AddBatchV_J_F_F_F_F_I;
    sElaMotionEventCallback.elastos_MotionEvent_addBatchV_J_LAVMEPC_I = &AwMotionEvent::AddBatchV_J_LAVMEPC_I;
    sElaMotionEventCallback.elastos_MotionEvent_toString = &AwMotionEvent::ToString;
    sElaMotionEventCallback.elastos_MotionEvent_axisToString = &AwMotionEvent::AxisToString;
    sElaMotionEventCallback.elastos_MotionEvent_axisFromString = &AwMotionEvent::AxisFromString;
    sElaMotionEventCallback.elastos_MotionEvent_writeToParcel = &AwMotionEvent::WriteToParcel;

    Elastos_MotionEvent_InitCallback((Handle32)&sElaMotionEventCallback);
    return &sElaMotionEventCallback;
}

static void* sPElaMotionEventCallback = AwMotionEvent::ElaMotionEventCallback_Init();

} // namespace Api
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH
