//This file is autogenerated for
//    ApplicationStatus.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_APPLICATIONSTATUS_CALLBACK_DEC_HH
#define ELASTOS_APPLICATIONSTATUS_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_ApplicationStatus_nativeOnApplicationStateChange(Int32 newState);
    extern void Elastos_ApplicationStatus_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Base {

struct ElaApplicationStatusCallback
{
    void (*elastos_ApplicationStatus_registerThreadSafeNativeApplicationStateListener)();
};

void* ApplicationStatus::ElaApplicationStatusCallback_Init()
{
    static ElaApplicationStatusCallback sElaApplicationStatusCallback;

    sElaApplicationStatusCallback.elastos_ApplicationStatus_registerThreadSafeNativeApplicationStateListener = &ApplicationStatus::RegisterThreadSafeNativeApplicationStateListener;

    Elastos_ApplicationStatus_InitCallback((Handle32)&sElaApplicationStatusCallback);
    return &sElaApplicationStatusCallback;
}

static void* sPElaApplicationStatusCallback = ApplicationStatus::ElaApplicationStatusCallback_Init();

} // namespace Base
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_APPLICATIONSTATUS_CALLBACK_DEC_HH
