//This file is autogenerated for
//    BuildInfo.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_BUILDINFO_CALLBACK_DEC_HH
#define ELASTOS_BUILDINFO_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_BuildInfo_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Base {

struct ElaBuildInfoCallback
{
    String (*elastos_BuildInfo_getDevice)();
    String (*elastos_BuildInfo_getBrand)();
    String (*elastos_BuildInfo_getAndroidBuildId)();
    String (*elastos_BuildInfo_getAndroidBuildFingerprint)();
    String (*elastos_BuildInfo_getDeviceModel)();
    String (*elastos_BuildInfo_getPackageVersionCode)(IInterface* context);
    String (*elastos_BuildInfo_getPackageVersionName)(IInterface* context);
    String (*elastos_BuildInfo_getPackageLabel)(IInterface* context);
    String (*elastos_BuildInfo_getPackageName)(IInterface* context);
    String (*elastos_BuildInfo_getBuildType)();
    Int32 (*elastos_BuildInfo_getSdkInt)();
};

void* BuildInfo::ElaBuildInfoCallback_Init()
{
    static ElaBuildInfoCallback sElaBuildInfoCallback;

    sElaBuildInfoCallback.elastos_BuildInfo_getDevice = &BuildInfo::GetDevice;
    sElaBuildInfoCallback.elastos_BuildInfo_getBrand = &BuildInfo::GetBrand;
    sElaBuildInfoCallback.elastos_BuildInfo_getAndroidBuildId = &BuildInfo::GetAndroidBuildId;
    sElaBuildInfoCallback.elastos_BuildInfo_getAndroidBuildFingerprint = &BuildInfo::GetAndroidBuildFingerprint;
    sElaBuildInfoCallback.elastos_BuildInfo_getDeviceModel = &BuildInfo::GetDeviceModel;
    sElaBuildInfoCallback.elastos_BuildInfo_getPackageVersionCode = &BuildInfo::GetPackageVersionCode;
    sElaBuildInfoCallback.elastos_BuildInfo_getPackageVersionName = &BuildInfo::GetPackageVersionName;
    sElaBuildInfoCallback.elastos_BuildInfo_getPackageLabel = &BuildInfo::GetPackageLabel;
    sElaBuildInfoCallback.elastos_BuildInfo_getPackageName = &BuildInfo::GetPackageName;
    sElaBuildInfoCallback.elastos_BuildInfo_getBuildType = &BuildInfo::GetBuildType;
    sElaBuildInfoCallback.elastos_BuildInfo_getSdkInt = &BuildInfo::GetSdkInt;

    Elastos_BuildInfo_InitCallback((Handle32)&sElaBuildInfoCallback);
    return &sElaBuildInfoCallback;
}

static void* sPElaBuildInfoCallback = BuildInfo::ElaBuildInfoCallback_Init();

} // namespace Base
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_BUILDINFO_CALLBACK_DEC_HH
