//This file is autogenerated for
//    PathUtils.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_PATHUTILS_CALLBACK_DEC_HH
#define ELASTOS_PATHUTILS_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_PathUtils_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Base {

struct ElaPathUtilsCallback
{
    String (*elastos_PathUtils_getDataDirectory)(IInterface* appContext);
    String (*elastos_PathUtils_getDatabaseDirectory)(IInterface* appContext);
    String (*elastos_PathUtils_getCacheDirectory)(IInterface* appContext);
    String (*elastos_PathUtils_getDownloadsDirectory)(IInterface* appContext);
    String (*elastos_PathUtils_getNativeLibraryDirectory)(IInterface* appContext);
    String (*elastos_PathUtils_getExternalStorageDirectory)();
};

void* PathUtils::ElaPathUtilsCallback_Init()
{
    static ElaPathUtilsCallback sElaPathUtilsCallback;

    sElaPathUtilsCallback.elastos_PathUtils_getDataDirectory = &PathUtils::GetDataDirectory;
    sElaPathUtilsCallback.elastos_PathUtils_getDatabaseDirectory = &PathUtils::GetDatabaseDirectory;
    sElaPathUtilsCallback.elastos_PathUtils_getCacheDirectory = &PathUtils::GetCacheDirectory;
    sElaPathUtilsCallback.elastos_PathUtils_getDownloadsDirectory = &PathUtils::GetDownloadsDirectory;
    sElaPathUtilsCallback.elastos_PathUtils_getNativeLibraryDirectory = &PathUtils::GetNativeLibraryDirectory;
    sElaPathUtilsCallback.elastos_PathUtils_getExternalStorageDirectory = &PathUtils::GetExternalStorageDirectory;

    Elastos_PathUtils_InitCallback((Handle32)&sElaPathUtilsCallback);
    return &sElaPathUtilsCallback;
}

static void* sPElaPathUtilsCallback = PathUtils::ElaPathUtilsCallback_Init();

} // namespace Base
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_PATHUTILS_CALLBACK_DEC_HH
