//This file is autogenerated for
//    PathService.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_PATHSERVICE_CALLBACK_DEC_HH
#define ELASTOS_PATHSERVICE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_PathService_nativeOverride(Int32 what,const String& path);
#ifdef __cplusplus
}
#endif


#endif //ELASTOS_PATHSERVICE_CALLBACK_DEC_HH
