//This file is autogenerated for
//    BitmapHelper.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_BITMAPHELPER_CALLBACK_DEC_HH
#define ELASTOS_BITMAPHELPER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_BitmapHelper_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Ui {
namespace Gfx {

struct ElaBitmapHelperCallback
{
    AutoPtr<IInterface> (*elastos_BitmapHelper_createBitmap)(Int32 width, Int32 height, Int32 bitmapFormatValue);
    AutoPtr<IInterface> (*elastos_BitmapHelper_decodeDrawableResource)(const String& name, Int32 reqWidth, Int32 reqHeight);
    Int32 (*elastos_BitmapHelper_getBitmapFormatForConfig)(Int32 bitmapConfig);
};

void* BitmapHelper::ElaBitmapHelperCallback_Init()
{
    static ElaBitmapHelperCallback sElaBitmapHelperCallback;

    sElaBitmapHelperCallback.elastos_BitmapHelper_createBitmap = &BitmapHelper::CreateBitmap;
    sElaBitmapHelperCallback.elastos_BitmapHelper_decodeDrawableResource = &BitmapHelper::DecodeDrawableResource;
    sElaBitmapHelperCallback.elastos_BitmapHelper_getBitmapFormatForConfig = &BitmapHelper::GetBitmapFormatForConfig;

    Elastos_BitmapHelper_InitCallback((Handle32)&sElaBitmapHelperCallback);
    return &sElaBitmapHelperCallback;
}

static void* sPElaBitmapHelperCallback = BitmapHelper::ElaBitmapHelperCallback_Init();

} // namespace Gfx
} // namespace Ui
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_BITMAPHELPER_CALLBACK_DEC_HH
