//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    DeviceDisplayInfo.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_DEVICEDISPLAYINFO_CALLBACK_DEC_HH
#define ELASTOS_DEVICEDISPLAYINFO_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_DeviceDisplayInfo_nativeUpdateSharedDeviceDisplayInfo(IInterface* caller,Int32 displayHeight,Int32 displayWidth,Int32 physicalDisplayHeight,Int32 physicalDisplayWidth,Int32 bitsPerPixel,Int32 bitsPerComponent,Double dipScale,Int32 smallestDIPWidth,Int32 rotationDegrees);
    extern void Elastos_DeviceDisplayInfo_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Ui {
namespace Gfx {

struct ElaDeviceDisplayInfoCallback
{
    Int32 (*elastos_DeviceDisplayInfo_getDisplayHeight)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getDisplayWidth)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getPhysicalDisplayHeight)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getPhysicalDisplayWidth)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getBitsPerPixel)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getBitsPerComponent)(IInterface* obj);
    Double (*elastos_DeviceDisplayInfo_getDIPScale)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getSmallestDIPWidth)(IInterface* obj);
    Int32 (*elastos_DeviceDisplayInfo_getRotationDegrees)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_DeviceDisplayInfo_create)(IInterface* context);
};

void* DeviceDisplayInfo::ElaDeviceDisplayInfoCallback_Init()
{
    static ElaDeviceDisplayInfoCallback sElaDeviceDisplayInfoCallback;

    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getDisplayHeight = &DeviceDisplayInfo::GetDisplayHeight;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getDisplayWidth = &DeviceDisplayInfo::GetDisplayWidth;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getPhysicalDisplayHeight = &DeviceDisplayInfo::GetPhysicalDisplayHeight;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getPhysicalDisplayWidth = &DeviceDisplayInfo::GetPhysicalDisplayWidth;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getBitsPerPixel = &DeviceDisplayInfo::GetBitsPerPixel;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getBitsPerComponent = &DeviceDisplayInfo::GetBitsPerComponent;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getDIPScale = &DeviceDisplayInfo::GetDIPScale;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getSmallestDIPWidth = &DeviceDisplayInfo::GetSmallestDIPWidth;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_getRotationDegrees = &DeviceDisplayInfo::GetRotationDegrees;
    sElaDeviceDisplayInfoCallback.elastos_DeviceDisplayInfo_create = &DeviceDisplayInfo::Create;

    Elastos_DeviceDisplayInfo_InitCallback((HANDLE)&sElaDeviceDisplayInfoCallback);
    return &sElaDeviceDisplayInfoCallback;
}

static void* sPElaDeviceDisplayInfoCallback = DeviceDisplayInfo::ElaDeviceDisplayInfoCallback_Init();

} // namespace Gfx
} // namespace Ui
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_DEVICEDISPLAYINFO_CALLBACK_DEC_HH
