//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    LocalizationUtils.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_LOCALIZATIONUTILS_CALLBACK_DEC_HH
#define ELASTOS_LOCALIZATIONUTILS_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Int32 Elastos_LocalizationUtils_nativeGetFirstStrongCharacterDirection(const String& string);
    extern String Elastos_LocalizationUtils_nativeGetDurationString(Int64 timeInMillis);
    extern void Elastos_LocalizationUtils_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Ui {
namespace Base {

struct ElaLocalizationUtilsCallback
{
    String (*elastos_LocalizationUtils_getDefaultLocale)();
    AutoPtr<IInterface> (*elastos_LocalizationUtils_getJavaLocale)(const String& language, const String& country, const String& variant);
    String (*elastos_LocalizationUtils_getDisplayNameForLocale)(IInterface* locale, IInterface* displayLocale);
    Boolean (*elastos_LocalizationUtils_isLayoutRtl)();
};

void* LocalizationUtils::ElaLocalizationUtilsCallback_Init()
{
    static ElaLocalizationUtilsCallback sElaLocalizationUtilsCallback;

    sElaLocalizationUtilsCallback.elastos_LocalizationUtils_getDefaultLocale = &LocalizationUtils::GetDefaultLocale;
    sElaLocalizationUtilsCallback.elastos_LocalizationUtils_getJavaLocale = &LocalizationUtils::GetJavaLocale;
    sElaLocalizationUtilsCallback.elastos_LocalizationUtils_getDisplayNameForLocale = &LocalizationUtils::GetDisplayNameForLocale;
    sElaLocalizationUtilsCallback.elastos_LocalizationUtils_isLayoutRtl = &LocalizationUtils::IsLayoutRtl;

    Elastos_LocalizationUtils_InitCallback((Handle32)&sElaLocalizationUtilsCallback);
    return &sElaLocalizationUtilsCallback;
}

static void* sPElaLocalizationUtilsCallback = LocalizationUtils::ElaLocalizationUtilsCallback_Init();

} // namespace Base
} // namespace Ui
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_LOCALIZATIONUTILS_CALLBACK_DEC_HH
