//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    TouchDevice.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_TOUCHDEVICE_CALLBACK_DEC_HH
#define ELASTOS_TOUCHDEVICE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_TouchDevice_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Ui {
namespace Base {

struct ElaTouchDeviceCallback
{
    Int32 (*elastos_TouchDevice_maxTouchPoints)(IInterface* context);
};

void* TouchDevice::ElaTouchDeviceCallback_Init()
{
    static ElaTouchDeviceCallback sElaTouchDeviceCallback;

    sElaTouchDeviceCallback.elastos_TouchDevice_maxTouchPoints = &TouchDevice::MaxTouchPoints;

    Elastos_TouchDevice_InitCallback((HANDLE)&sElaTouchDeviceCallback);
    return &sElaTouchDeviceCallback;
}

static void* sPElaTouchDeviceCallback = TouchDevice::ElaTouchDeviceCallback_Init();

} // namespace Base
} // namespace Ui
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_TOUCHDEVICE_CALLBACK_DEC_HH
