/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_GridLayoutDemo_R_H__
#define __Elastos_DevSamples_GridLayoutDemo_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace GridLayoutDemo {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class drawable {
        public: static const int earth = 0x7f020000;
        public: static const int icon = 0x7f020001;
        public: static const int transformer = 0x7f020002;
        public: static const int wunderland = 0x7f020003;
    };
    public: class id {
        public: static const int layout = 0x7f050000;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};

#endif // __Elastos_DevSamples_GridLayoutDemo_R_H__
