#include "R.h"
namespace Elastos {
namespace Droid {
namespace Launcher2 {

const int R::anim::fade_in_fast;
const int R::anim::fade_out_fast;
const int R::array::extra_wallpapers;
const int R::array::wallpapers;
const int R::attr::cellCountX;
const int R::attr::cellCountY;
const int R::attr::cellHeight;
const int R::attr::cellWidth;
const int R::attr::className;
const int R::attr::clingFocusedX;
const int R::attr::clingFocusedY;
const int R::attr::container;
const int R::attr::defaultScreen;
const int R::attr::direction;
const int R::attr::drawIdentifier;
const int R::attr::heightGap;
const int R::attr::icon;
const int R::attr::key;
const int R::attr::maxAppCellCountX;
const int R::attr::maxAppCellCountY;
const int R::attr::maxGap;
const int R::attr::packageName;
const int R::attr::pageLayoutHeightGap;
const int R::attr::pageLayoutPaddingBottom;
const int R::attr::pageLayoutPaddingLeft;
const int R::attr::pageLayoutPaddingRight;
const int R::attr::pageLayoutPaddingTop;
const int R::attr::pageLayoutWidthGap;
const int R::attr::pageSpacing;
const int R::attr::screen;
const int R::attr::scrollIndicatorPaddingLeft;
const int R::attr::scrollIndicatorPaddingRight;
const int R::attr::sourceImageViewId;
const int R::attr::sourceViewId;
const int R::attr::spanX;
const int R::attr::spanY;
const int R::attr::strokeColor;
const int R::attr::strokeTextColor;
const int R::attr::strokeWidth;
const int R::attr::title;
const int R::attr::uri;
const int R::attr::value;
const int R::attr::widgetCellHeightGap;
const int R::attr::widgetCellWidthGap;
const int R::attr::widgetCountX;
const int R::attr::widgetCountY;
const int R::attr::widthGap;
const int R::attr::x;
const int R::attr::y;
const int R::bool_::allow_rotation;
const int R::bool_::config_largeHeap;
const int R::bool_::config_useCustomClings;
const int R::bool_::config_useDropTargetDownTransition;
const int R::bool_::config_workspaceFadeAdjacentScreens;
const int R::bool_::hotseat_transpose_layout_with_orientation;
const int R::bool_::is_large_screen;
const int R::color::appwidget_error_color;
const int R::color::bubble_dark_background;
const int R::color::delete_target_hover_tint;
const int R::color::info_target_hover_tint;
const int R::color::workspace_all_apps_and_delete_zone_text_color;
const int R::color::workspace_all_apps_and_delete_zone_text_shadow_color;
const int R::color::workspace_icon_text_color;
const int R::dimen::all_apps_button_vertical_padding;
const int R::dimen::app_icon_drawable_padding;
const int R::dimen::app_icon_drawable_padding_land;
const int R::dimen::app_icon_padding_top;
const int R::dimen::app_icon_size;
const int R::dimen::app_widget_preview_label_margin_left;
const int R::dimen::app_widget_preview_label_margin_right;
const int R::dimen::app_widget_preview_label_margin_top;
const int R::dimen::app_widget_preview_padding_left;
const int R::dimen::app_widget_preview_padding_right;
const int R::dimen::app_widget_preview_padding_top;
const int R::dimen::apps_customize_cell_height;
const int R::dimen::apps_customize_cell_width;
const int R::dimen::apps_customize_max_gap;
const int R::dimen::apps_customize_pageLayoutHeightGap;
const int R::dimen::apps_customize_pageLayoutPaddingBottom;
const int R::dimen::apps_customize_pageLayoutPaddingLeft;
const int R::dimen::apps_customize_pageLayoutPaddingRight;
const int R::dimen::apps_customize_pageLayoutPaddingTop;
const int R::dimen::apps_customize_pageLayoutWidthGap;
const int R::dimen::apps_customize_tab_bar_height;
const int R::dimen::apps_customize_tab_bar_margin_top;
const int R::dimen::apps_customize_widget_cell_height_gap;
const int R::dimen::apps_customize_widget_cell_width_gap;
const int R::dimen::button_bar_height;
const int R::dimen::button_bar_height_bottom_padding;
const int R::dimen::button_bar_height_plus_padding;
const int R::dimen::button_bar_height_top_padding;
const int R::dimen::button_bar_width_left_padding;
const int R::dimen::button_bar_width_right_padding;
const int R::dimen::cell_layout_bottom_padding;
const int R::dimen::cell_layout_bottom_padding_land;
const int R::dimen::cell_layout_bottom_padding_port;
const int R::dimen::cell_layout_left_padding;
const int R::dimen::cell_layout_left_padding_land;
const int R::dimen::cell_layout_left_padding_port;
const int R::dimen::cell_layout_right_padding;
const int R::dimen::cell_layout_right_padding_land;
const int R::dimen::cell_layout_right_padding_port;
const int R::dimen::cell_layout_top_padding;
const int R::dimen::cell_layout_top_padding_land;
const int R::dimen::cell_layout_top_padding_port;
const int R::dimen::clingPunchThroughGraphicCenterRadius;
const int R::dimen::cling_text_block_offset_x;
const int R::dimen::cling_text_block_offset_y;
const int R::dimen::dragViewOffsetX;
const int R::dimen::dragViewOffsetY;
const int R::dimen::dragViewScale;
const int R::dimen::drop_target_drag_padding;
const int R::dimen::folderClingMarginTop;
const int R::dimen::folder_cell_height;
const int R::dimen::folder_cell_width;
const int R::dimen::folder_height_gap;
const int R::dimen::folder_icon_padding_top;
const int R::dimen::folder_name_padding;
const int R::dimen::folder_padding;
const int R::dimen::folder_preview_padding;
const int R::dimen::folder_preview_size;
const int R::dimen::folder_width_gap;
const int R::dimen::hotseat_cell_height;
const int R::dimen::hotseat_cell_width;
const int R::dimen::hotseat_height_gap;
const int R::dimen::hotseat_width_gap;
const int R::dimen::profile_badge_margin;
const int R::dimen::profile_badge_size;
const int R::dimen::qsb_bar_height;
const int R::dimen::qsb_bar_height_inset;
const int R::dimen::qsb_padding_left;
const int R::dimen::qsb_padding_right;
const int R::dimen::qsb_voice_proxy_padding_right;
const int R::dimen::reveal_radius;
const int R::dimen::scroll_zone;
const int R::dimen::search_bar_height;
const int R::dimen::shortcut_preview_padding_left;
const int R::dimen::shortcut_preview_padding_right;
const int R::dimen::shortcut_preview_padding_top;
const int R::dimen::toolbar_button_horizontal_padding;
const int R::dimen::toolbar_button_vertical_padding;
const int R::dimen::toolbar_external_icon_height;
const int R::dimen::toolbar_external_icon_width;
const int R::dimen::wallpaper_chooser_grid_height;
const int R::dimen::wallpaper_chooser_grid_width;
const int R::dimen::workspace_bottom_padding;
const int R::dimen::workspace_bottom_padding_land;
const int R::dimen::workspace_bottom_padding_port;
const int R::dimen::workspace_cell_height;
const int R::dimen::workspace_cell_height_land;
const int R::dimen::workspace_cell_height_port;
const int R::dimen::workspace_cell_width;
const int R::dimen::workspace_cell_width_land;
const int R::dimen::workspace_cell_width_port;
const int R::dimen::workspace_divider_padding_bottom;
const int R::dimen::workspace_divider_padding_left;
const int R::dimen::workspace_divider_padding_right;
const int R::dimen::workspace_divider_padding_top;
const int R::dimen::workspace_divider_width;
const int R::dimen::workspace_height_gap;
const int R::dimen::workspace_height_gap_land;
const int R::dimen::workspace_height_gap_port;
const int R::dimen::workspace_icon_text_size;
const int R::dimen::workspace_left_padding;
const int R::dimen::workspace_left_padding_land;
const int R::dimen::workspace_left_padding_port;
const int R::dimen::workspace_max_gap;
const int R::dimen::workspace_overscroll_drawable_padding;
const int R::dimen::workspace_page_spacing;
const int R::dimen::workspace_right_padding;
const int R::dimen::workspace_right_padding_land;
const int R::dimen::workspace_right_padding_port;
const int R::dimen::workspace_spring_loaded_page_spacing;
const int R::dimen::workspace_top_padding;
const int R::dimen::workspace_top_padding_land;
const int R::dimen::workspace_top_padding_port;
const int R::dimen::workspace_width_gap;
const int R::dimen::workspace_width_gap_land;
const int R::dimen::workspace_width_gap_port;
const int R::drawable::all_apps_button_icon;
const int R::drawable::apps_customize_bg;
const int R::drawable::bg_appwidget_error;
const int R::drawable::bg_cling1;
const int R::drawable::bg_cling2;
const int R::drawable::bg_cling3;
const int R::drawable::bg_cling4;
const int R::drawable::bg_cling5;
const int R::drawable::btn_cling_normal;
const int R::drawable::btn_cling_pressed;
const int R::drawable::cling;
const int R::drawable::cling_button_bg;
const int R::drawable::default_wallpaper;
const int R::drawable::default_wallpaper_small;
const int R::drawable::divider_launcher_holo;
const int R::drawable::flying_icon_bg;
const int R::drawable::flying_icon_bg_pressed;
const int R::drawable::focusable_view_bg;
const int R::drawable::focused_bg;
const int R::drawable::grid_focused;
const int R::drawable::grid_pressed;
const int R::drawable::grid_selected;
const int R::drawable::hand;
const int R::drawable::home_press;
const int R::drawable::homescreen_blue_normal_holo;
const int R::drawable::homescreen_blue_strong_holo;
const int R::drawable::hotseat_scrubber_holo;
const int R::drawable::hotseat_track_holo;
const int R::drawable::ic_allapps;
const int R::drawable::ic_allapps_pressed;
const int R::drawable::ic_home_all_apps_holo_dark;
const int R::drawable::ic_home_search_normal_holo;
const int R::drawable::ic_home_voice_search_holo;
const int R::drawable::ic_launcher_clear_active_holo;
const int R::drawable::ic_launcher_clear_normal_holo;
const int R::drawable::ic_launcher_info_active_holo;
const int R::drawable::ic_launcher_info_normal_holo;
const int R::drawable::ic_launcher_market_holo;
const int R::drawable::ic_launcher_trashcan_active_holo;
const int R::drawable::ic_launcher_trashcan_normal_holo;
const int R::drawable::info_target_selector;
const int R::drawable::overscroll_glow_left;
const int R::drawable::overscroll_glow_right;
const int R::drawable::page_hover_left_holo;
const int R::drawable::page_hover_right_holo;
const int R::drawable::portal_container_holo;
const int R::drawable::portal_ring_inner_holo;
const int R::drawable::portal_ring_inner_nolip_holo;
const int R::drawable::portal_ring_outer_holo;
const int R::drawable::portal_ring_rest;
const int R::drawable::remove_target_selector;
const int R::drawable::search_frame;
const int R::drawable::tab_selected_focused_holo;
const int R::drawable::tab_selected_holo;
const int R::drawable::tab_selected_pressed_focused_holo;
const int R::drawable::tab_selected_pressed_holo;
const int R::drawable::tab_unselected_focused_holo;
const int R::drawable::tab_unselected_holo;
const int R::drawable::tab_unselected_pressed_focused_holo;
const int R::drawable::tab_unselected_pressed_holo;
const int R::drawable::tab_widget_indicator_selector;
const int R::drawable::uninstall_target_selector;
const int R::drawable::wallpaper_gallery_background;
const int R::drawable::wallpaper_gallery_item;
const int R::drawable::wallpaper_picker_preview;
const int R::drawable::widget_container_holo;
const int R::drawable::widget_preview_tile;
const int R::drawable::widget_resize_frame_holo;
const int R::drawable::widget_resize_handle_bottom;
const int R::drawable::widget_resize_handle_left;
const int R::drawable::widget_resize_handle_right;
const int R::drawable::widget_resize_handle_top;
const int R::drawable::workspace_bg;
const int R::id::all_apps_cling;
const int R::id::all_apps_cling_add_item;
const int R::id::all_apps_cling_title;
const int R::id::animation_buffer;
const int R::id::application_icon;
const int R::id::apps_customize_content;
const int R::id::apps_customize_pane;
const int R::id::apps_customize_pane_content;
const int R::id::apps_customize_progress_bar;
const int R::id::cell1;
const int R::id::cell2;
const int R::id::cell3;
const int R::id::cell4;
const int R::id::cell5;
const int R::id::cling_dismiss;
const int R::id::delete_target_text;
const int R::id::dock_divider;
const int R::id::drag_layer;
const int R::id::drag_target_bar;
const int R::id::folder_cling;
const int R::id::folder_cling_create_folder;
const int R::id::folder_cling_title;
const int R::id::folder_content;
const int R::id::folder_icon_name;
const int R::id::folder_name;
const int R::id::gallery;
const int R::id::horizontal;
const int R::id::hotseat;
const int R::id::info_target_text;
const int R::id::label;
const int R::id::launcher;
const int R::id::layout;
const int R::id::market_button;
const int R::id::paged_view_indicator;
const int R::id::preview_background;
const int R::id::provider;
const int R::id::provider_icon;
const int R::id::qsb_bar;
const int R::id::qsb_divider;
const int R::id::qsb_search_bar;
const int R::id::search_button;
const int R::id::search_button_container;
const int R::id::set;
const int R::id::tabs_container;
const int R::id::vertical;
const int R::id::voice_button;
const int R::id::voice_button_container;
const int R::id::voice_button_proxy;
const int R::id::wallpaper_chooser_fragment;
const int R::id::wallpaper_image;
const int R::id::widget_dims;
const int R::id::widget_name;
const int R::id::widget_preview;
const int R::id::workspace;
const int R::id::workspace_cling;
const int R::integer::apps_customize_cling_focused_x;
const int R::integer::apps_customize_cling_focused_y;
const int R::integer::apps_customize_maxCellCountX;
const int R::integer::apps_customize_maxCellCountY;
const int R::integer::apps_customize_widget_cell_count_x;
const int R::integer::apps_customize_widget_cell_count_y;
const int R::integer::cell_count_x;
const int R::integer::cell_count_y;
const int R::integer::config_allAppsBatchLoadDelay;
const int R::integer::config_allAppsBatchSize;
const int R::integer::config_appsCustomizeDragSlopeThreshold;
const int R::integer::config_appsCustomizeFadeInTime;
const int R::integer::config_appsCustomizeFadeOutTime;
const int R::integer::config_appsCustomizeSpringLoadedBgAlpha;
const int R::integer::config_appsCustomizeWorkspaceAnimationStagger;
const int R::integer::config_appsCustomizeWorkspaceShrinkTime;
const int R::integer::config_appsCustomizeZoomInTime;
const int R::integer::config_appsCustomizeZoomOutTime;
const int R::integer::config_appsCustomizeZoomScaleFactor;
const int R::integer::config_cameraDistance;
const int R::integer::config_dragFadeOutAlpha;
const int R::integer::config_dragFadeOutDuration;
const int R::integer::config_dragOutlineFadeTime;
const int R::integer::config_dragOutlineMaxAlpha;
const int R::integer::config_dropAnimMaxDist;
const int R::integer::config_dropAnimMaxDuration;
const int R::integer::config_dropAnimMinDuration;
const int R::integer::config_dropTargetBgTransitionDuration;
const int R::integer::config_flingToDeleteMinVelocity;
const int R::integer::config_folderAnimDuration;
const int R::integer::config_tabTransitionDuration;
const int R::integer::config_workspaceAppsCustomizeAnimationStagger;
const int R::integer::config_workspaceSpringLoadShrinkPercentage;
const int R::integer::config_workspaceUnshrinkTime;
const int R::integer::folder_max_count_x;
const int R::integer::folder_max_count_y;
const int R::integer::folder_max_num_items;
const int R::integer::hotseat_all_apps_index;
const int R::integer::hotseat_cell_count;
const int R::integer::hotseat_item_scale_percentage;
const int R::layout::add_list_item;
const int R::layout::all_apps_cling;
const int R::layout::application;
const int R::layout::apps_customize_application;
const int R::layout::apps_customize_pane;
const int R::layout::apps_customize_progressbar;
const int R::layout::apps_customize_widget;
const int R::layout::appwidget_error;
const int R::layout::custom_workspace_cling;
const int R::layout::drop_target_bar;
const int R::layout::external_widget_drop_list_item;
const int R::layout::folder_cling;
const int R::layout::folder_icon;
const int R::layout::hotseat;
const int R::layout::launcher;
const int R::layout::market_button;
const int R::layout::qsb_bar;
const int R::layout::rename_folder;
const int R::layout::scroll_indicator;
const int R::layout::search_bar;
const int R::layout::tab_widget_indicator;
const int R::layout::user_folder;
const int R::layout::wallpaper_chooser;
const int R::layout::wallpaper_chooser_base;
const int R::layout::wallpaper_item;
const int R::layout::workspace;
const int R::layout::workspace_cling;
const int R::layout::workspace_divider;
const int R::layout::workspace_screen;
const int R::mipmap::ic_launcher_application;
const int R::mipmap::ic_launcher_home;
const int R::mipmap::ic_launcher_wallpaper;
const int R::string::accessibility_all_apps_button;
const int R::string::accessibility_delete_button;
const int R::string::accessibility_search_button;
const int R::string::accessibility_voice_search_button;
const int R::string::activity_not_found;
const int R::string::all_apps_button_label;
const int R::string::all_apps_cling_add_item;
const int R::string::all_apps_cling_title;
const int R::string::all_apps_home_button_label;
const int R::string::application_name;
const int R::string::apps_customize_apps_scroll_format;
const int R::string::apps_customize_widgets_scroll_format;
const int R::string::cab_app_selection_text;
const int R::string::cab_folder_selection_text;
const int R::string::cab_menu_app_info;
const int R::string::cab_menu_delete_app;
const int R::string::cab_shortcut_selection_text;
const int R::string::cab_widget_selection_text;
const int R::string::cancel_action;
const int R::string::chooser_wallpaper;
const int R::string::cling_dismiss;
const int R::string::completely_out_of_space;
const int R::string::custom_workspace_cling_description_1;
const int R::string::custom_workspace_cling_description_2;
const int R::string::custom_workspace_cling_title_1;
const int R::string::custom_workspace_cling_title_2;
const int R::string::default_scroll_format;
const int R::string::delete_target_label;
const int R::string::delete_target_uninstall_label;
const int R::string::delete_zone_label_all_apps;
const int R::string::delete_zone_label_all_apps_system_app;
const int R::string::delete_zone_label_workspace;
const int R::string::dream_name;
const int R::string::dummy_custom_cling_error_message;
const int R::string::external_drop_widget_error;
const int R::string::external_drop_widget_pick_format;
const int R::string::external_drop_widget_pick_title;
const int R::string::folder_cling_create_folder;
const int R::string::folder_cling_move_item;
const int R::string::folder_cling_title;
const int R::string::folder_closed;
const int R::string::folder_hint_text;
const int R::string::folder_name;
const int R::string::folder_name_format;
const int R::string::folder_opened;
const int R::string::folder_renamed;
const int R::string::folder_tap_to_close;
const int R::string::folder_tap_to_rename;
const int R::string::gadget_error_text;
const int R::string::group_applications;
const int R::string::group_shortcuts;
const int R::string::group_wallpapers;
const int R::string::group_widgets;
const int R::string::help_url;
const int R::string::home;
const int R::string::hotseat_out_of_space;
const int R::string::info_target_label;
const int R::string::invalid_hotseat_item;
const int R::string::long_press_widget_to_add;
const int R::string::market;
const int R::string::menu_add;
const int R::string::menu_help;
const int R::string::menu_item_add_item;
const int R::string::menu_manage_apps;
const int R::string::menu_notifications;
const int R::string::menu_search;
const int R::string::menu_settings;
const int R::string::menu_wallpaper;
const int R::string::out_of_space;
const int R::string::permdesc_install_shortcut;
const int R::string::permdesc_read_settings;
const int R::string::permdesc_uninstall_shortcut;
const int R::string::permdesc_write_settings;
const int R::string::permlab_install_shortcut;
const int R::string::permlab_read_settings;
const int R::string::permlab_uninstall_shortcut;
const int R::string::permlab_write_settings;
const int R::string::pick_wallpaper;
const int R::string::rename_action;
const int R::string::rename_folder_label;
const int R::string::rename_folder_title;
const int R::string::shortcut_duplicate;
const int R::string::shortcut_installed;
const int R::string::shortcut_uninstalled;
const int R::string::title_select_application;
const int R::string::title_select_shortcut;
const int R::string::uid_name;
const int R::string::uninstall_system_app_text;
const int R::string::wallpaper_instructions;
const int R::string::widget_dims_format;
const int R::string::widgets_tab_label;
const int R::string::workspace_cling_move_item;
const int R::string::workspace_cling_open_all_apps;
const int R::string::workspace_cling_title;
const int R::string::workspace_description_format;
const int R::string::workspace_scroll_format;
const int R::style::ClingButton;
const int R::style::ClingText;
const int R::style::ClingTitleText;
const int R::style::CustomClingText;
const int R::style::CustomClingTitleText;
const int R::style::DropTargetButton;
const int R::style::DropTargetButtonContainer;
const int R::style::MarketButton;
const int R::style::QSBBar;
const int R::style::SearchButton;
const int R::style::SearchDropTargetBar;
const int R::style::TabIndicator;
const int R::style::TabIndicator_AppsCustomize;
const int R::style::Theme;
const int R::style::Theme_WallpaperPicker;
const int R::style::WorkspaceIcon;
const int R::style::WorkspaceIcon_Landscape;
const int R::style::WorkspaceIcon_Landscape_AppsCustomize;
const int R::style::WorkspaceIcon_Landscape_Folder;
const int R::style::WorkspaceIcon_Portrait;
const int R::style::WorkspaceIcon_Portrait_AppsCustomize;
const int R::style::WorkspaceIcon_Portrait_Folder;
const int R::xml::default_workspace;
const int R::xml::update_workspace;
const int R::xml::wallpaper_picker_preview;
const int R::styleable::AppsCustomizePagedView[8] = {
            0x7f010018, 0x7f010019, 0x7f01001a, 0x7f01001b,
            0x7f01001c, 0x7f01001d, 0x7f01001e, 0x7f01001f
        };

const int R::styleable::AppsCustomizePagedView_clingFocusedX;
const int R::styleable::AppsCustomizePagedView_clingFocusedY;
const int R::styleable::AppsCustomizePagedView_maxAppCellCountX;
const int R::styleable::AppsCustomizePagedView_maxAppCellCountY;
const int R::styleable::AppsCustomizePagedView_widgetCellHeightGap;
const int R::styleable::AppsCustomizePagedView_widgetCellWidthGap;
const int R::styleable::AppsCustomizePagedView_widgetCountX;
const int R::styleable::AppsCustomizePagedView_widgetCountY;
const int R::styleable::CellLayout[5] = {
            0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009,
            0x7f01000a
        };

const int R::styleable::CellLayout_cellHeight;
const int R::styleable::CellLayout_cellWidth;
const int R::styleable::CellLayout_heightGap;
const int R::styleable::CellLayout_maxGap;
const int R::styleable::CellLayout_widthGap;
const int R::styleable::Cling[1] = {
            0x7f010002
        };

const int R::styleable::Cling_drawIdentifier;
const int R::styleable::CustomClingText[0] = {

        };

const int R::styleable::CustomClingTitleText[0] = {

        };

const int R::styleable::DrawableStateProxyView[1] = {
            0x7f010001
        };

const int R::styleable::DrawableStateProxyView_sourceViewId;
const int R::styleable::Extra[2] = {
            0x7f01002b, 0x7f01002c
        };

const int R::styleable::Extra_key;
const int R::styleable::Extra_value;
const int R::styleable::Favorite[11] = {
            0x7f010020, 0x7f010021, 0x7f010022, 0x7f010023,
            0x7f010024, 0x7f010025, 0x7f010026, 0x7f010027,
            0x7f010028, 0x7f010029, 0x7f01002a
        };

const int R::styleable::Favorite_className;
const int R::styleable::Favorite_container;
const int R::styleable::Favorite_icon;
const int R::styleable::Favorite_packageName;
const int R::styleable::Favorite_screen;
const int R::styleable::Favorite_spanX;
const int R::styleable::Favorite_spanY;
const int R::styleable::Favorite_title;
const int R::styleable::Favorite_uri;
const int R::styleable::Favorite_x;
const int R::styleable::Favorite_y;
const int R::styleable::HandleView[1] = {
            0x7f010000
        };

const int R::styleable::HandleView_direction;
const int R::styleable::HolographicLinearLayout[1] = {
            0x7f01000e
        };

const int R::styleable::HolographicLinearLayout_sourceImageViewId;
const int R::styleable::Hotseat[2] = {
            0x7f010004, 0x7f010005
        };

const int R::styleable::Hotseat_cellCountX;
const int R::styleable::Hotseat_cellCountY;
const int R::styleable::PagedView[9] = {
            0x7f01000f, 0x7f010010, 0x7f010011, 0x7f010012,
            0x7f010013, 0x7f010014, 0x7f010015, 0x7f010016,
            0x7f010017
        };

const int R::styleable::PagedView_pageLayoutHeightGap;
const int R::styleable::PagedView_pageLayoutPaddingBottom;
const int R::styleable::PagedView_pageLayoutPaddingLeft;
const int R::styleable::PagedView_pageLayoutPaddingRight;
const int R::styleable::PagedView_pageLayoutPaddingTop;
const int R::styleable::PagedView_pageLayoutWidthGap;
const int R::styleable::PagedView_pageSpacing;
const int R::styleable::PagedView_scrollIndicatorPaddingLeft;
const int R::styleable::PagedView_scrollIndicatorPaddingRight;
const int R::styleable::StrokedTextView[3] = {
            0x7f01000b, 0x7f01000c, 0x7f01000d
        };

const int R::styleable::StrokedTextView_strokeColor;
const int R::styleable::StrokedTextView_strokeTextColor;
const int R::styleable::StrokedTextView_strokeWidth;
const int R::styleable::Workspace[3] = {
            0x7f010003, 0x7f010004, 0x7f010005
        };

const int R::styleable::Workspace_cellCountX;
const int R::styleable::Workspace_cellCountY;
const int R::styleable::Workspace_defaultScreen;
};
};
};

