
#ifndef __ELASTOS_DROID_SYSTEMUI_RECENT_TASKDESCRIPTION_H__
#define __ELASTOS_DROID_SYSTEMUI_RECENT_TASKDESCRIPTION_H__

#include "_Elastos.Droid.SystemUI.h"
#include "Elastos.Droid.Content.h"
#include "Elastos.Droid.Graphics.h"
#include "Elastos.CoreLibrary.Core.h"
#include "elastos/droid/graphics/drawable/ColorDrawable.h"

using Elastos::Droid::Content::IIntent;
using Elastos::Droid::Content::Pm::IResolveInfo;
using Elastos::Droid::Graphics::Drawable::IDrawable;
using Elastos::Droid::SystemUI::Recent::ITaskDescription;
using Elastos::Core::ICharSequence;

namespace Elastos {
namespace Droid {
namespace SystemUI {
namespace Recent {

class TaskDescription
    : public Object
    , public ITaskDescription
{
public:
    CAR_INTERFACE_DECL()

    TaskDescription(
        /* [in] */ Int32 _taskId,
        /* [in] */ Int32 _persistentTaskId,
        /* [in] */ IResolveInfo* _resolveInfo,
        /* [in] */ IIntent* _intent,
        /* [in] */ const String& _packageName,
        /* [in] */ ICharSequence* _description,
        /* [in] */ Int32 _userId);

    TaskDescription();

    CARAPI SetLoaded(
        /* [in] */ Boolean loaded);

    CARAPI IsLoaded(
        /* [out] */ Boolean* isLoaded);

    CARAPI IsNull(
        /* [out] */ Boolean* isNull);

    // mark all these as locked?
    CARAPI GetLabel(
        /* [out] */ ICharSequence** isLoaded);

    CARAPI SetLabel(
        /* [in] */ ICharSequence* label);

    CARAPI GetIcon(
        /* [out] */ IDrawable** icon);

    CARAPI SetIcon(
        /* [in] */ IDrawable* icon);

    CARAPI SetThumbnail(
        /* [in] */ IDrawable* thumbnail);

    CARAPI GetThumbnail(
        /* [out] */ IDrawable** thumbnail);

    CARAPI ToString(
        /* [out] */ String* str);
public:
    AutoPtr<IResolveInfo> mResolveInfo;
    const Int32 mTaskId; // application task id for curating apps
    const Int32 mPersistentTaskId; // persistent id
    AutoPtr<IIntent> mIntent; // launch intent for application
    String mPackageName; // used to override animations (see onClick())
    AutoPtr<ICharSequence> mDescription;
    const Int32 mUserId;

private:
    AutoPtr<IDrawable> mThumbnail; // generated by Activity.onCreateThumbnail()
    AutoPtr<IDrawable> mIcon; // application package icon
    AutoPtr<ICharSequence> mLabel; // application package label
    Boolean mLoaded;
};

} // namespace Recent
} // namespace SystemUI
} // namespace Droid
} // namespace Elastos

#endif //__ELASTOS_DROID_SYSTEMUI_RECENT_TASKDESCRIPTION_H__