/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_SpinnerDemo_R_H__
#define __Elastos_Droid_DevSamples_SpinnerDemo_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace SpinnerDemo {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int hideButton = 0x7f050005;
        public: static const int radioFemale = 0x7f050003;
        public: static const int radioMale = 0x7f050002;
        public: static const int radioSex = 0x7f050001;
        public: static const int spinner = 0x7f050000;
        public: static const int toastButton = 0x7f050004;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
        public: static const int simple_spinner_item = 0x7f030001;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
        public: static const int hello = 0x7f040001;
        public: static const int planet_prompt = 0x7f040002;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_SpinnerDemo_R_H__
