//This file is autogenerated for
//    CancellationSignal.class
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH
#define ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_CancellationSignal_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Api {

//TODO no user found for this callback function in chromium_org
struct ElaCancellationSignalCallback
{
    Boolean (*elastos_CancellationSignal_isCanceled)(IInterface* obj);
    void (*elastos_CancellationSignal_throwIfCanceled)(IInterface* obj);
    void (*elastos_CancellationSignal_cancel)(IInterface* obj);
    void (*elastos_CancellationSignal_setOnCancelListener)(IInterface* obj, IInterface* p0);
    AutoPtr<IInterface> (*elastos_CancellationSignal_Constructor)();
};

void* AwCancellationSignal::ElaCancellationSignalCallback_Init()
{
    static ElaCancellationSignalCallback sElaCancellationSignalCallback;

    sElaCancellationSignalCallback.elastos_CancellationSignal_isCanceled = &AwCancellationSignal::IsCanceled;
    sElaCancellationSignalCallback.elastos_CancellationSignal_throwIfCanceled = &AwCancellationSignal::ThrowIfCanceled;
    sElaCancellationSignalCallback.elastos_CancellationSignal_cancel = &AwCancellationSignal::Cancel;
    sElaCancellationSignalCallback.elastos_CancellationSignal_setOnCancelListener = &AwCancellationSignal::SetOnCancelListener;
    sElaCancellationSignalCallback.elastos_CancellationSignal_Constructor = &AwCancellationSignal::Constructor;
    //no user for these callbacks in chromium.so
    //Elastos_CancellationSignal_InitCallback((Handle32)&sElaCancellationSignalCallback);
    return &sElaCancellationSignalCallback;
}

//static void* sPElaCancellationSignalCallback = AwCancellationSignal::ElaCancellationSignalCallback_Init();

} // namespace Api
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH
