//=========================================================================
// Copyright (C) 2012 The Elastos Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//=========================================================================

//This file is autogenerated for
//    AndroidCertVerifyResult.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_ANDROIDCERTVERIFYRESULT_CALLBACK_DEC_HH
#define ELASTOS_ANDROIDCERTVERIFYRESULT_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_AndroidCertVerifyResult_InitCallback(HANDLE cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Net {

struct ElaAndroidCertVerifyResultCallback
{
    Int32 (*elastos_AndroidCertVerifyResult_getStatus)(IInterface* obj);
    Boolean (*elastos_AndroidCertVerifyResult_isIssuedByKnownRoot)(IInterface* obj);
    AutoPtr<ArrayOf<AutoPtr<ArrayOf<Byte> > > > (*elastos_AndroidCertVerifyResult_getCertificateChainEncoded)(IInterface* obj);
};

void* ElastosCertVerifyResult::ElaElastosCertVerifyResultCallback_Init()
{
    static ElaAndroidCertVerifyResultCallback sElaAndroidCertVerifyResultCallback;

    sElaAndroidCertVerifyResultCallback.elastos_AndroidCertVerifyResult_getStatus = &ElastosCertVerifyResult::GetStatus;
    sElaAndroidCertVerifyResultCallback.elastos_AndroidCertVerifyResult_isIssuedByKnownRoot = &ElastosCertVerifyResult::IsIssuedByKnownRoot;
    sElaAndroidCertVerifyResultCallback.elastos_AndroidCertVerifyResult_getCertificateChainEncoded = &ElastosCertVerifyResult::GetCertificateChainEncoded;

    Elastos_AndroidCertVerifyResult_InitCallback((HANDLE)&sElaAndroidCertVerifyResultCallback);
    return &sElaAndroidCertVerifyResultCallback;
}

static void* sPElaElastosCertVerifyResultCallback = ElastosCertVerifyResult::ElaElastosCertVerifyResultCallback_Init();

} // namespace Net
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_ANDROIDCERTVERIFYRESULT_CALLBACK_DEC_HH
