/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_WifiDisplayDemo_R_H__
#define __Elastos_Droid_DevSamples_WifiDisplayDemo_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace WifiDisplayDemo {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int ic_sysbar_back = 0x7f020000;
        public: static const int ic_sysbar_home = 0x7f020001;
        public: static const int ic_sysbar_menu = 0x7f020002;
        public: static const int icon = 0x7f020003;
    };
    public: class id {
        public: static const int ConnectButton = 0x7f050007;
        public: static const int DisconnectButton = 0x7f050008;
        public: static const int DisplayListView = 0x7f05000a;
        public: static const int ForgetButton = 0x7f050009;
        public: static const int GetStatusButton = 0x7f050005;
        public: static const int InfoTextView = 0x7f050000;
        public: static const int OffButton = 0x7f050003;
        public: static const int OnButton = 0x7f050002;
        public: static const int OnOffRadioGroup = 0x7f050001;
        public: static const int RenameButton = 0x7f050006;
        public: static const int ScanButton = 0x7f050004;
    };
    public: class layout {
        public: static const int list_item = 0x7f030000;
        public: static const int main = 0x7f030001;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_WifiDisplayDemo_R_H__
