/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_Droid_DevSamples_ActivityTest_R_H__
#define __Elastos_Droid_DevSamples_ActivityTest_R_H__
namespace Elastos {
namespace Droid {
namespace DevSamples {
namespace ActivityTest {
class R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int RestoreInstanceState = 0x7f060000;
        public: static const int menu_item_share = 0x7f060003;
        public: static const int newActivity = 0x7f060001;
        public: static const int receivetext = 0x7f060002;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
        public: static const int main2 = 0x7f030001;
    };
    public: class menu {
        public: static const int share_menu = 0x7f050000;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};
};

#endif // __Elastos_Droid_DevSamples_ActivityTest_R_H__
