//This file is autogenerated for
//    BatteryStatusManager.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_BATTERYSTATUSMANAGER_CALLBACK_DEC_HH
#define ELASTOS_BATTERYSTATUSMANAGER_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_BatteryStatusManager_nativeGotBatteryStatus(IInterface* caller,Handle64 nativeBatteryStatusManager,Boolean charging,Double chargingTime,Double dischargingTime,Double level);
    extern void Elastos_BatteryStatusManager_InitCallback(Handle64 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Webview {
namespace Chromium {
namespace Content {
namespace Browser {

struct ElaBatteryStatusManagerCallback
{
    AutoPtr<IInterface> (*elastos_BatteryStatusManager_getInstance)(IInterface* appContext);
    Boolean (*elastos_BatteryStatusManager_start)(IInterface* obj, Handle64 nativePtr);
    void (*elastos_BatteryStatusManager_stop)(IInterface* obj);
};

void* BatteryStatusManager::ElaBatteryStatusManagerCallback_Init()
{
    static ElaBatteryStatusManagerCallback sElaBatteryStatusManagerCallback;

    sElaBatteryStatusManagerCallback.elastos_BatteryStatusManager_getInstance = &BatteryStatusManager::GetInstance;
    sElaBatteryStatusManagerCallback.elastos_BatteryStatusManager_start = &BatteryStatusManager::Start;
    sElaBatteryStatusManagerCallback.elastos_BatteryStatusManager_stop = &BatteryStatusManager::Stop;

    Elastos_BatteryStatusManager_InitCallback((Handle64)&sElaBatteryStatusManagerCallback);
    return &sElaBatteryStatusManagerCallback;
}

static void* sPElaBatteryStatusManagerCallback = BatteryStatusManager::ElaBatteryStatusManagerCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Chromium
} // namespace Webview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_BATTERYSTATUSMANAGER_CALLBACK_DEC_HH
