/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_NotificationDemo_R_H__
#define __Elastos_DevSamples_NotificationDemo_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace NotificationDemo {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class drawable {
        public: static const int icon = 0x7f020000;
    };
    public: class id {
        public: static const int cancelNotificationButton = 0x7f050004;
        public: static const int myTextView = 0x7f050000;
        public: static const int startNotificationButton = 0x7f050002;
        public: static const int statusBarNotificationButton = 0x7f050001;
        public: static const int updateNotificationButton = 0x7f050003;
    };
    public: class layout {
        public: static const int main = 0x7f030000;
        public: static const int notification = 0x7f030001;
    };
    public: class string {
        public: static const int app_name = 0x7f040000;
    };
};
};
};
};

#endif // __Elastos_DevSamples_NotificationDemo_R_H__
